/**
 * Major names older accounts may hold in the legacy `User.major` string, which the profile maps onto official
 * Acalog names on read (server/auth/profile.ts, findProgramByName). Test data only: nothing in the app offers or
 * validates against these lists any more (pickers use programNames().majors plus a UI-only "Undecided").
 */

/** The hackathon app's sign-up list (main:frontend/lib/utils.ts MAJORS). */
export const HACKATHON_MAJOR_NAMES = [
  "Africana Studies",
  "Anthropology",
  "Art",
  "Biology",
  "Chemistry",
  "Chinese Studies",
  "Classical Languages and Literature",
  "Classical Studies",
  "Communication Studies",
  "Computer Science",
  "East Asian Studies",
  "Economics",
  "Educational Studies",
  "English",
  "Environmental Studies",
  "Film/Media/Digital Studies",
  "French & Francophone Studies",
  "Gender & Sexuality Studies",
  "German Studies",
  "Hispanic Studies",
  "History",
  "Interdisciplinary Studies",
  "Mathematics",
  "Music",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Religious Studies",
  "Sociology",
  "Theatre",
  "Undecided",
] as const;

/**
 * The interim sign-up list of the rebuild's first wave (davidson.edu/majors-minors-programs "Major" badges,
 * verified 2026-09-30), used until the Acalog names landed.
 */
export const INTERIM_MAJOR_NAMES = [
  "Africana Studies",
  "Anthropology",
  "Arab Studies",
  "Art",
  "Biology",
  "Chemistry",
  "Chinese Studies",
  "Classical Languages and Literature",
  "Classical Studies",
  "Communication Studies",
  "Computer Science",
  "East Asian Studies",
  "Economics",
  "Educational Studies",
  "English",
  "Environmental Studies",
  "Film, Media, and Digital Studies",
  "French & Francophone Studies",
  "Gender & Sexuality Studies",
  "Genomics, Bioinformatics",
  "German Studies",
  "Global Literary Theory",
  "Hispanic Studies",
  "History",
  "Interdisciplinary Studies",
  "Latin American, Latinx, and Caribbean Studies",
  "Mathematics",
  "Music",
  "Philosophy",
  "Philosophy, Politics, and Economics",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Religious Studies",
  "Russian Studies",
  "Sociology",
  "Theatre",
  "Undecided",
] as const;
