import "server-only";
import * as z from "zod";
import { getFlags } from "@/lib/flags";
import { termLabel, type TermCode } from "@/lib/term";
import { aiFailure, type AiProvenance, type AiResult, type ProfessorSummary } from "@/lib/types/ai";
import type { Course, Instructor } from "@/lib/types/catalog";
import type { InstructorRating } from "@/lib/types/ratings";
import { hashInput, readShared, writeShared } from "@/server/ai/cache";
import {
  AI_MIN_CALL_MS,
  AI_MODEL,
  AI_REQUEST_BUDGET_MS,
  MIN_RATINGS_FOR_SUMMARY,
  TTL_MS,
} from "@/server/ai/config";
import { callModel, okResult } from "@/server/ai/features/common";
import {
  OutputSchema,
  professorSummaryRequest,
  PROMPT_VERSION,
} from "@/server/ai/prompts/professor-summary";
import { aiConfigured } from "@/server/ai/provider";
import { fetchTeacherReviews, type ReviewFetcher } from "@/server/ai/reviews";
import {
  anyOf,
  cleanList,
  cleanParagraph,
  copiesLongRun,
  forbiddenClaims,
  hasLongQuote,
  sentences,
  words,
  type SentenceFilter,
} from "@/server/ai/sanitize";
import { budgetFailure, recordUsage } from "@/server/ai/usage";
import { getCourse, resolveTerms, searchCourses } from "@/server/catalog";
import { now } from "@/server/clock";
import { ApiError } from "@/server/http/errors";
import { ExternalFetchError } from "@/server/http/external";
import { getCourseRatings } from "@/server/rmp/course";
import { normalizeName } from "@/server/rmp/normalize";

/**
 * Professor review summaries (PLAN §6.1 W6 feature 5), LAST and behind RMP_SUMMARIES_ENABLED (default off; it
 * also needs RMP_ENABLED and AI_ENABLED). With the flag off nothing here runs: the route answers "disabled" before
 * calling in, and the weekly job returns { skipped: "disabled" } without reading anything.
 *
 *   - Only matched RMP profiles with at least 5 ratings; shared per profile (key "rmp:<legacyId>"), 7 days.
 *   - Generated by the weekly job only (GET /api/cron/ai/professor-summaries); the route only reads.
 *   - Review text is fetched for one prompt (<untrusted_reviews>) and never stored beyond it.
 *   - Output checks: no names, no links, no quotation over 20 words and no run of more than 20 words copied from a
 *     review (else invalid and a 24 h negative entry). Names: the instructor's name is replaced by "the
 *     professor" (case-sensitive, capitalised name tokens of 3+ letters, shorter ones only after a title or as
 *     part of the full name, so "an engaging class" stays as it is); a title with any other capitalised name
 *     ("Professor Smith") makes the answer invalid; a sentence or theme with a word the reviews use as a name
 *     (a capitalised word inside a review sentence: a TA, a student, other staff) is dropped.
 *   - The job stops at its deadline (no call is started with less than AI_MIN_CALL_MS left) and on the first
 *     rejected request (a deployment problem: every other call would fail the same way); API errors are never
 *     remembered as negative entries.
 */

export interface ProfessorSummaryResult {
  summary: ProfessorSummary;
  provenance: AiProvenance;
}

export const SUMMARY_NOT_AVAILABLE =
  "There is no AI summary of reviews for this instructor yet. Summaries are written once a week.";
export const TOO_FEW_RATINGS = `AI summaries need at least ${MIN_RATINGS_FOR_SUMMARY} ratings.`;
export const NOT_MATCHED = "MakeItSo has no confirmed ratings profile for this instructor.";

export function summaryKey(legacyId: number): string {
  return `rmp:${legacyId}`;
}

function sameInstructor(a: Instructor, b: Instructor): boolean {
  return (
    normalizeName(a.first) === normalizeName(b.first) &&
    normalizeName(a.last) === normalizeName(b.last)
  );
}

const TITLE = String.raw`(?:Dr|Prof|Professor|Mr|Mrs|Ms|Mx)\.?`;
const escapeRegExp = (text: string) => text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/** "mei" → "Mei", "McDonald" stays. */
function capitalised(token: string): string {
  return token.charAt(0).toUpperCase() + token.slice(1);
}

/**
 * Replace the instructor's name with "the professor": the full name, a title with any of its tokens, and name
 * tokens of 3+ letters alone. Case-sensitive (capitalised forms only), so ordinary words ("an", "may") stay.
 */
export function withoutName(text: string, names: readonly string[]): string {
  const tokens = [
    ...new Set(
      names
        .flatMap((name) => name.split(/[\s-]+/))
        .map((token) => token.trim())
        .filter((token) => token.length >= 2)
        .flatMap((token) => [token, capitalised(token)]),
    ),
  ].sort((a, b) => b.length - a.length);
  if (tokens.length === 0) return text;
  const any = tokens.map(escapeRegExp).join("|");
  const long = tokens
    .filter((token) => token.length >= 3)
    .map(escapeRegExp)
    .join("|");
  const full = names
    .map((name) => name.trim())
    .filter(Boolean)
    .map((name) => escapeRegExp(capitalised(name)))
    .join(String.raw`[\s-]+`);
  const parts = [
    // "Dr. Ada Lovelace", "Professor An"
    String.raw`${TITLE}\s+(?:${any})(?:[\s-]+(?:${any}))*`,
    // "Ada Lovelace", "Mei An"
    ...(full ? [full] : []),
    // "Lovelace", "Lovelace's" (3+ letters)
    ...(long ? [String.raw`(?:${long})`] : []),
  ];
  const pattern = new RegExp(String.raw`(?<![\p{L}])(?:${parts.join("|")})(?![\p{L}])`, "gu");
  return (
    text
      .replace(pattern, "the professor")
      .replace(/\bthe professor(?:'s)?\s+the professor\b/g, "the professor")
      // At the start of the text or of a sentence: "The professor".
      .replace(/(^|[.!?]\s+)the professor/g, "$1The professor")
  );
}

/**
 * A title followed by a capitalised name (after the instructor's name was replaced: someone else). "professor"
 * takes no period, so "…the professor. Students say…" is not a title.
 */
const TITLED_NAME = new RegExp(
  String.raw`\b(?:(?:[Dd]r|[Pp]rof|Mr|Mrs|Ms|Mx)\.?|[Pp]rofessor)\s+\p{Lu}\p{Ll}[\p{L}'’-]*`,
  "u",
);

/** Capitalised words that may appear inside review sentences without being a person's name. */
const NOT_NAMES = new Set([
  "I",
  "TA",
  "TAs",
  "OK",
  "Professor",
  "Prof",
  "Dr",
  "Davidson",
  "College",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
  "Fall",
  "Spring",
  "Summer",
  "Winter",
]);

/** The words the reviews use as names: capitalised words that do not start a sentence. */
export function reviewNameWords(reviews: readonly string[]): Set<string> {
  const out = new Set<string>();
  for (const review of reviews) {
    for (const sentence of sentences(review)) {
      const tokens = sentence
        .split(/\s+/)
        .map((token) => token.replace(/^[^\p{L}]+|[^\p{L}]+$/gu, "").replace(/['’]s$/u, ""))
        .filter(Boolean);
      tokens.forEach((token, index) => {
        if (index > 0 && /^\p{Lu}\p{Ll}/u.test(token) && !NOT_NAMES.has(token)) out.add(token);
      });
    }
  }
  return out;
}

/** Drop text containing one of `nameWords` (as a capitalised word). */
function mentions(nameWords: ReadonlySet<string>): SentenceFilter {
  return (text) =>
    text
      .split(/\s+/)
      .map((token) => token.replace(/^[^\p{L}]+|[^\p{L}]+$/gu, "").replace(/['’]s$/u, ""))
      .some((token) => nameWords.has(token));
}

/** Post-validate a summary; null when it quotes or copies reviews, names someone, or nothing usable is left. */
export function cleanProfessorSummary(
  raw: ProfessorSummary,
  context: { names: readonly string[]; reviews: readonly string[] },
): ProfessorSummary | null {
  const rawText = `${raw.summary} ${raw.themes.join(" ")}`;
  if (hasLongQuote(rawText) || copiesLongRun(rawText, context.reviews)) return null;
  const summaryText = withoutName(raw.summary, context.names);
  const themes = raw.themes.map((theme) => withoutName(theme, context.names));
  if ([summaryText, ...themes].some((text) => TITLED_NAME.test(text))) return null;
  const drop = anyOf(forbiddenClaims, mentions(reviewNameWords(context.reviews)));
  const summary = cleanParagraph(summaryText, 500, drop);
  if (!summary || words(summary).length < 5) return null;
  return {
    summary,
    themes: cleanList(themes, { maxItems: 5, maxLength: 60, drop }),
  };
}

/** POST /api/ai/professor-summary (after the gate): reads the weekly entry for a course's instructor. */
export async function readProfessorSummary(
  userId: string,
  input: { termCode: TermCode; courseCode: string; instructor: Instructor },
): Promise<AiResult<ProfessorSummaryResult>> {
  const course = await getCourse(input.termCode, input.courseCode);
  if (!course) {
    throw new ApiError(
      404,
      "not_found",
      `${input.courseCode} is not offered in ${termLabel(input.termCode)}.`,
    );
  }
  const teaches = course.sections.some((s) =>
    s.instructors.some((i) => sameInstructor(i, input.instructor)),
  );
  if (!teaches || input.instructor.isStaff) {
    throw new ApiError(
      404,
      "not_found",
      "That instructor does not teach this course in that term.",
    );
  }
  const ratings = await getCourseRatings(course);
  const rating = ratings.find((r) => sameInstructor(r.instructor, input.instructor));
  if (!rating || rating.status !== "matched" || !rating.rmp)
    return aiFailure("unavailable", NOT_MATCHED);
  if (rating.rmp.numRatings < MIN_RATINGS_FOR_SUMMARY)
    return aiFailure("unavailable", TOO_FEW_RATINGS);

  const entry = await readShared<ProfessorSummary>(
    "professor-summary",
    summaryKey(rating.rmp.legacyId),
  );
  if (!entry) return aiFailure("unavailable", SUMMARY_NOT_AVAILABLE);
  if (entry.hidden) {
    return aiFailure(
      "unavailable",
      "This AI summary was reported by students and is hidden pending review.",
    );
  }
  if (entry.status !== "ok" || !entry.data) return aiFailure("unavailable", SUMMARY_NOT_AVAILABLE);
  await recordUsage({
    userId,
    feature: "professor-summary",
    kind: "cache-hit",
    servedModel: entry.provenance.model,
  });
  return okResult(
    { summary: entry.data, provenance: entry.provenance },
    { servedModel: entry.provenance.model, fallbackUsed: entry.fallbackUsed, cached: true },
  );
}

// ---- Weekly job ---------------------------------------------------------------------------------------------------

export const ProfessorSummaryJobResultSchema = z.object({
  skipped: z.enum(["disabled", "not_configured"]).nullable(),
  /** Matched profiles with enough ratings among the current and registration terms' instructors. */
  profiles: z.number().int().min(0),
  generated: z.number().int().min(0),
  /** Entries that are current (or hidden pending review, or remembered as failed for a day). */
  fresh: z.number().int().min(0),
  failed: z.number().int().min(0),
  /** "error": the API rejected a request (a deployment problem), so the run stopped. */
  stoppedEarly: z.enum(["deadline", "budget", "error"]).nullable(),
});
export type ProfessorSummaryJobResult = z.infer<typeof ProfessorSummaryJobResultSchema>;

export interface ProfessorSummaryJobOptions {
  /** All model work is over this many ms after the start (default AI_REQUEST_BUDGET_MS of the route's 120 s). */
  timeBudgetMs?: number;
  fetchReviews?: ReviewFetcher;
}

/** An entry this close to its end is regenerated by the job (the job runs weekly; entries live 7 days). */
const REFRESH_WITHIN_MS = 2 * 86_400_000;

async function coursesOf(term: TermCode): Promise<Course[]> {
  const out: Course[] = [];
  for (let page = 1; page <= 20; page++) {
    const result = await searchCourses({ term, pageSize: 100, page });
    for (const item of result.items) {
      const course = await getCourse(term, item.code);
      if (course) out.push(course);
    }
    if (page * 100 >= result.total) break;
  }
  return out;
}

export async function runProfessorSummaryJob(
  options: ProfessorSummaryJobOptions = {},
): Promise<ProfessorSummaryJobResult> {
  const result: ProfessorSummaryJobResult = {
    skipped: null,
    profiles: 0,
    generated: 0,
    fresh: 0,
    failed: 0,
    stoppedEarly: null,
  };
  const flags = getFlags();
  if (!flags.ai || !flags.rmpSummaries) return { ...result, skipped: "disabled" };
  if (!aiConfigured()) return { ...result, skipped: "not_configured" };
  const fetchReviews = options.fetchReviews ?? fetchTeacherReviews;
  const deadlineAt = Date.now() + (options.timeBudgetMs ?? AI_REQUEST_BUDGET_MS);

  const resolved = await resolveTerms();
  const profiles = new Map<number, InstructorRating>();
  for (const term of [...new Set([resolved.current, resolved.registration])]) {
    for (const course of await coursesOf(term)) {
      for (const rating of await getCourseRatings(course)) {
        if (
          rating.status === "matched" &&
          rating.rmp &&
          rating.rmp.numRatings >= MIN_RATINGS_FOR_SUMMARY
        ) {
          profiles.set(rating.rmp.legacyId, rating);
        }
      }
    }
  }
  result.profiles = profiles.size;

  for (const [legacyId, rating] of [...profiles].sort(([a], [b]) => a - b)) {
    if (deadlineAt - Date.now() < AI_MIN_CALL_MS) {
      result.stoppedEarly = "deadline";
      break;
    }
    const key = summaryKey(legacyId);
    const inputHash = hashInput({
      feature: "professor-summary",
      promptVersion: PROMPT_VERSION,
      model: AI_MODEL,
      legacyId,
      numRatings: rating.rmp?.numRatings ?? 0,
    });
    const entry = await readShared<ProfessorSummary>("professor-summary", key);
    if (
      entry &&
      (entry.hidden ||
        (entry.inputHash === inputHash &&
          (entry.status !== "ok" ||
            entry.validUntil.getTime() - now().getTime() > REFRESH_WITHIN_MS)))
    ) {
      result.fresh++;
      continue;
    }
    if (await budgetFailure()) {
      result.stoppedEarly = "budget";
      break;
    }
    let reviews;
    try {
      reviews = await fetchReviews(legacyId);
    } catch (error) {
      // An upstream failure skips this profile; anything else (a missing test fixture, a bug) propagates.
      if (!(error instanceof ExternalFetchError)) throw error;
      console.error(`[ai] professor-summary: reviews for ${legacyId} unavailable (${error.kind})`);
      result.failed++;
      continue;
    }
    if (reviews.length < MIN_RATINGS_FOR_SUMMARY) {
      result.failed++;
      continue;
    }
    const outcome = await callModel(OutputSchema, professorSummaryRequest({ reviews }), {
      userId: null,
      deadlineAt,
    });
    const names = [rating.instructor.first, rating.instructor.last];
    const summary =
      outcome.kind === "ok"
        ? cleanProfessorSummary(outcome.data, { names, reviews: reviews.map((r) => r.text) })
        : null;
    const status = outcome.kind === "ok" ? (summary ? "ok" : "invalid") : outcome.kind;
    if (status === "ok" && summary) {
      const stored = await writeShared("professor-summary", key, {
        inputHash,
        promptVersion: PROMPT_VERSION,
        status: "ok",
        data: summary,
        servedModel: outcome.servedModel,
        fallbackUsed: outcome.fallbackUsed,
        ttlMs: TTL_MS.professorSummary,
      });
      // Null: hidden pending review meanwhile (nothing written over it).
      if (stored) result.generated++;
      else result.fresh++;
      continue;
    }
    result.failed++;
    if (outcome.kind !== "ok" && outcome.origin === "rejected") {
      result.stoppedEarly = "error";
      break;
    }
    // Only answers the model gave are remembered (never API errors).
    const answered = outcome.kind === "ok" || outcome.origin === "response";
    if (answered && (status === "refused" || status === "invalid")) {
      await writeShared("professor-summary", key, {
        inputHash,
        promptVersion: PROMPT_VERSION,
        status,
        data: null,
        message: aiFailure(status).message,
        servedModel: outcome.servedModel,
        fallbackUsed: outcome.fallbackUsed,
        ttlMs: TTL_MS.negative,
      });
    }
  }
  return result;
}
