import type { Session } from "next-auth";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { withCatalogDb } from "../catalog/db";
import { aiRequest, bodyOf, errorOf, insertStudent, sessionFor, stubAuthEnv } from "./helpers";
import * as cronRoute from "@/app/api/cron/ai/professor-summaries/route";
import * as route from "@/app/api/ai/professor-summary/route";
import * as report from "@/app/api/ai/report/route";
import { ProfessorSummaryResultSchema } from "@/lib/api/ai";
import { RMP_DAVIDSON_SCHOOL_ID } from "@/lib/types/ratings";
import AiCache from "@/models/AiCache";
import AiUsage from "@/models/AiUsage";
import RmpTeacher from "@/models/RmpTeacher";
import {
  cleanProfessorSummary,
  NOT_MATCHED,
  runProfessorSummaryJob,
  SUMMARY_NOT_AVAILABLE,
  TOO_FEW_RATINGS,
} from "@/server/ai/features/professor-summary";
import { mockAiRequests, resetMockAi, setMockAiScenario } from "@/server/ai/mock";
import { fetchTeacherReviews, TEACHER_REVIEWS_QUERY, type Review } from "@/server/ai/reviews";
import { getCourse } from "@/server/catalog";
import { ExternalFetchError, isDefinedRoute } from "@/server/http";
import { indexTokens, normalizeName } from "@/server/rmp/normalize";

/**
 * Professor review summaries (PLAN §6.1 W6 feature 5): behind RMP_SUMMARIES_ENABLED (default off), 5+ ratings,
 * generated by the weekly job only, review text never stored beyond the prompt. Reviews here are synthetic.
 */

const auth = vi.hoisted(() => ({ session: null as Session | null }));
vi.mock("next-auth", async (importOriginal) => ({
  ...(await importOriginal<Record<string, unknown>>()),
  getServerSession: async () => auth.session,
}));
vi.mock("next/server", async (importOriginal) => ({
  ...(await importOriginal<Record<string, unknown>>()),
  connection: async () => undefined,
}));

withCatalogDb();

const CRON_SECRET = "test-cron-secret-0123456789";
const REVIEW_TEXT =
  "SYNTHETIC-REVIEW explains recursion with drawings on the board and answers every question patiently in office hours, and the weekly labs connect lectures to programs";
const reviews = (n: number): Review[] =>
  Array.from({ length: n }, (_, i) => ({
    course: "CSC221",
    text: `${REVIEW_TEXT} number ${i + 1}.`,
  }));

beforeEach(() => {
  stubAuthEnv();
  vi.stubEnv("AI_PROVIDER", "mock");
});

afterEach(() => {
  auth.session = null;
  resetMockAi();
});

async function teacher(first: string, last: string, legacyId: number, numRatings: number) {
  await RmpTeacher.create({
    rmpId: `VGVhY2hlci0${legacyId}`,
    legacyId,
    firstName: first,
    lastName: last,
    normalizedFirst: normalizeName(first),
    normalizedLast: normalizeName(last),
    nameTokens: indexTokens(first, last),
    department: "Computer Science",
    schoolId: RMP_DAVIDSON_SCHOOL_ID,
    avgRating: 4.2,
    avgDifficulty: 3.1,
    numRatings,
    wouldTakeAgainPct: 80,
    fetchedAt: new Date("2026-09-28T00:00:00Z"),
  });
}

async function signIn() {
  const user = await insertStudent();
  auth.session = await sessionFor(user);
  return user;
}

const INSTRUCTOR = { first: "Katy", last: "Williams", isStaff: false };
async function reportIt(session: Session, key: string) {
  const previous = auth.session;
  auth.session = session;
  const res = await report.POST(aiRequest("/api/ai/report", { feature: "professor-summary", key }));
  auth.session = previous;
  return res;
}
const post = (body: unknown) => route.POST(aiRequest("/api/ai/professor-summary", body));
const ask = (instructor = INSTRUCTOR, courseCode = "CSC 221") =>
  post({ termCode: "202602", courseCode, instructor });

describe("with RMP_SUMMARIES_ENABLED off (the default) nothing runs", () => {
  it("the route answers disabled before reading anything", async () => {
    expect(isDefinedRoute(route.POST)).toBe(true);
    expect(route.maxDuration).toBe(120);
    await signIn();
    const res = await ask();
    expect(res.status).toBe(404);
    expect(await bodyOf(res)).toEqual({ kind: "disabled", message: "AI features are turned off." });
  });

  it("the weekly job skips without reading the catalog, the roster or any review", async () => {
    const fetchReviews = vi.fn(async () => reviews(6));
    expect(await runProfessorSummaryJob({ fetchReviews })).toEqual({
      skipped: "disabled",
      profiles: 0,
      generated: 0,
      fresh: 0,
      failed: 0,
      stoppedEarly: null,
    });
    expect(fetchReviews).not.toHaveBeenCalled();
    vi.stubEnv("CRON_SECRET", CRON_SECRET);
    const res = await cronRoute.GET(
      new Request("http://localhost/api/cron/ai/professor-summaries", {
        headers: { authorization: `Bearer ${CRON_SECRET}` },
      }),
    );
    expect(res.status).toBe(200);
    expect(await res.json()).toMatchObject({ skipped: "disabled" });
    expect(mockAiRequests()).toHaveLength(0);
  });
});

describe("with RMP_SUMMARIES_ENABLED on", () => {
  beforeEach(() => {
    vi.stubEnv("RMP_SUMMARIES_ENABLED", "true");
  });

  it("the weekly job writes shared summaries for matched profiles with 5+ ratings, never storing review text", async () => {
    await teacher("Katy", "Williams", 111, 12);
    const fetchReviews = vi.fn(async () => reviews(8));
    const result = await runProfessorSummaryJob({ fetchReviews });
    expect(result).toMatchObject({
      skipped: null,
      profiles: 1,
      generated: 1,
      failed: 0,
      stoppedEarly: null,
    });
    expect(fetchReviews).toHaveBeenCalledWith(111);

    const stored = await AiCache.find({ feature: "professor-summary" }).lean();
    expect(stored).toHaveLength(1);
    expect(stored[0]).toMatchObject({ scope: "shared", key: "rmp:111", status: "ok" });
    const everything = JSON.stringify([stored, await AiUsage.find().lean()]);
    expect(everything).not.toContain("SYNTHETIC-REVIEW");
    // The reviews reached the model as untrusted data.
    expect(JSON.stringify(mockAiRequests()[0]!.params.messages)).toContain("untrusted_reviews");

    expect(await runProfessorSummaryJob({ fetchReviews })).toMatchObject({
      generated: 0,
      fresh: 1,
    });
    expect(fetchReviews).toHaveBeenCalledTimes(1);
  });

  it("the route reads the weekly entry (it never generates)", async () => {
    await teacher("Katy", "Williams", 111, 12);
    await signIn();
    const before = await ask();
    expect(before.status).toBe(503);
    expect(await bodyOf(before)).toEqual({ kind: "unavailable", message: SUMMARY_NOT_AVAILABLE });
    expect(mockAiRequests()).toHaveLength(0);

    await runProfessorSummaryJob({ fetchReviews: async () => reviews(6) });
    const res = await ask();
    expect(res.status).toBe(200);
    const body = ProfessorSummaryResultSchema.parse(await bodyOf(res));
    expect(body).toMatchObject({
      kind: "ok",
      cached: true,
      data: { provenance: { promptVersion: "professor-summary/1" } },
    });
    if (body.kind !== "ok") throw new Error("expected ok");
    expect(JSON.stringify(body.data.summary)).not.toMatch(/Katy|Williams/);

    // "Report this" names the entry by the provenance it was shown; 3 distinct reporters hide it.
    for (let i = 0; i < 3; i++) {
      const reporter = await insertStudent({ email: `reporter-${i}@davidson.edu` });
      const reported = await reportIt(await sessionFor(reporter), body.data.provenance.inputHash);
      expect(reported.status).toBe(204);
    }
    const hidden = await ask();
    expect(hidden.status).toBe(503);
    expect((await bodyOf(hidden)).message).toMatch(/hidden pending review/);
  });

  it("needs a matched profile with at least 5 ratings, and an instructor of that course", async () => {
    await teacher("Katy", "Williams", 111, 4);
    await signIn();
    expect(await bodyOf(await ask())).toEqual({ kind: "unavailable", message: TOO_FEW_RATINGS });
    const course = await getCourse("202602", "CSC 121");
    const other = course!.sections[0]!.instructors[0]!;
    const unmatched = await ask(other, "CSC 121");
    expect(await bodyOf(unmatched)).toEqual({ kind: "unavailable", message: NOT_MATCHED });
    const wrong = await ask({ first: "Nobody", last: "Atall", isStaff: false });
    expect(wrong.status).toBe(404);
    expect((await errorOf(wrong)).code).toBe("not_found");
    expect(await runProfessorSummaryJob({ fetchReviews: async () => reviews(6) })).toMatchObject({
      profiles: 0,
    });
  });

  it("rejects summaries that quote or copy reviews (remembered for a day), and skips profiles whose reviews fail", async () => {
    await teacher("Katy", "Williams", 111, 12);
    setMockAiScenario("quote_reviews", { times: 1 });
    const quoted = await runProfessorSummaryJob({ fetchReviews: async () => reviews(6) });
    expect(quoted).toMatchObject({ generated: 0, failed: 1 });
    expect(await AiCache.findOne({ key: "rmp:111" }).lean()).toMatchObject({
      status: "invalid",
      data: null,
    });

    await AiCache.deleteMany({});
    vi.spyOn(console, "error").mockImplementation(() => undefined);
    const down = await runProfessorSummaryJob({
      fetchReviews: async () => {
        throw new ExternalFetchError(
          "ratemyprofessors",
          "https://www.ratemyprofessors.com/graphql",
          "timeout",
          "x",
        );
      },
    });
    expect(down).toMatchObject({ generated: 0, failed: 1 });
    const few = await runProfessorSummaryJob({ fetchReviews: async () => reviews(3) });
    expect(few).toMatchObject({ generated: 0, failed: 1 });
    await expect(
      runProfessorSummaryJob({
        fetchReviews: async () => {
          throw new TypeError("a bug");
        },
      }),
    ).rejects.toThrow("a bug");
  });

  it("stops on a request the API rejects and remembers no API error", async () => {
    await teacher("Katy", "Williams", 111, 12);
    const other = (await getCourse("202602", "CSC 121"))!.sections[0]!.instructors[0]!;
    await teacher(other.first, other.last, 222, 9);
    vi.spyOn(console, "error").mockImplementation(() => undefined);
    setMockAiScenario("bad_request");
    const fetchReviews = vi.fn(async () => reviews(6));
    const result = await runProfessorSummaryJob({ fetchReviews });
    expect(result).toMatchObject({ profiles: 2, stoppedEarly: "error", generated: 0, failed: 1 });
    // The second profile was not tried: every call would fail the same way.
    expect(mockAiRequests()).toHaveLength(1);
    expect(await AiCache.countDocuments()).toBe(0);

    // A transient error is not remembered either, and the run goes on to the next profile.
    setMockAiScenario("timeout", { times: 1 });
    const flaky = await runProfessorSummaryJob({ fetchReviews });
    expect(flaky).toMatchObject({ stoppedEarly: null, generated: 1, failed: 1 });
    expect(await AiCache.countDocuments({ status: "invalid" })).toBe(0);
    expect(await AiCache.countDocuments({ status: "ok" })).toBe(1);
  });

  it("a hidden summary stays hidden past its 7 days: the weekly job never regenerates it", async () => {
    await teacher("Katy", "Williams", 111, 12);
    await signIn();
    const fetchReviews = vi.fn(async () => reviews(6));
    await runProfessorSummaryJob({ fetchReviews });
    const res = await ask();
    const body = ProfessorSummaryResultSchema.parse(await bodyOf(res));
    if (body.kind !== "ok") throw new Error("expected ok");
    for (let i = 0; i < 3; i++) {
      const reporter = await insertStudent({ email: `hider-${i}@davidson.edu` });
      await reportIt(await sessionFor(reporter), body.data.provenance.inputHash);
    }
    const before = await AiCache.findOne({ key: "rmp:111" }).lean();
    expect(before!.hidden).toBe(true);

    vi.stubEnv("FIXTURES_NOW", "2026-10-20T12:00:00-04:00");
    const job = await runProfessorSummaryJob({ fetchReviews });
    expect(job).toMatchObject({ generated: 0, fresh: 1 });
    expect(fetchReviews).toHaveBeenCalledTimes(1);
    const hidden = await ask();
    expect(hidden.status).toBe(503);
    expect((await bodyOf(hidden)).message).toMatch(/hidden pending review/);
    const after = await AiCache.findOne({ key: "rmp:111" }).lean();
    expect(after?.provenance?.generatedAt).toEqual(before?.provenance?.generatedAt);
  });

  it("stops at the time budget", async () => {
    await teacher("Katy", "Williams", 111, 12);
    expect(
      await runProfessorSummaryJob({ timeBudgetMs: -1, fetchReviews: async () => reviews(6) }),
    ).toMatchObject({
      stoppedEarly: "deadline",
      generated: 0,
    });
  });
});

describe("cleanProfessorSummary", () => {
  const context = { names: ["Katy", "Williams"], reviews: [] as string[] };

  it("replaces the instructor's name and cleans the text", () => {
    expect(
      cleanProfessorSummary(
        {
          summary:
            "Reviewers say Prof. Katy Williams explains clearly; Williams is patient. See https://x.example",
          themes: ["Williams's drawings", "Patience"],
        },
        context,
      ),
    ).toEqual({
      summary: "Reviewers say the professor explains clearly; the professor is patient. See",
      themes: ["The professor's drawings", "Patience"],
    });
  });

  it("matches the instructor's name case-sensitively: short name parts only with a title or the full name", () => {
    const short = { names: ["Mei", "An"], reviews: [] as string[] };
    expect(
      cleanProfessorSummary(
        {
          summary:
            "Reviewers often mention an engaging class. Dr. An explains ideas slowly, and Mei An answers email quickly.",
          themes: ["An engaging style", "Mei's office hours"],
        },
        short,
      ),
    ).toEqual({
      summary:
        "Reviewers often mention an engaging class. The professor explains ideas slowly, and the professor answers email quickly.",
      themes: ["An engaging style", "The professor's office hours"],
    });
  });

  it("is invalid when it names someone else with a title", () => {
    expect(
      cleanProfessorSummary(
        {
          summary:
            "Reviewers say the class is well organized. Several suggest taking Professor Smith instead.",
          themes: [],
        },
        context,
      ),
    ).toBeNull();
    expect(
      cleanProfessorSummary(
        { summary: "Reviewers say lectures are clear and organized.", themes: ["Ask Dr. Jones"] },
        context,
      ),
    ).toBeNull();
    // "…the professor. Students…" is not a title.
    expect(
      cleanProfessorSummary(
        {
          summary: "Reviewers praise Williams. Students say lectures are clear and well organized.",
          themes: [],
        },
        context,
      )?.summary,
    ).toBe("Reviewers praise the professor. Students say lectures are clear and well organized.");
  });

  it("drops sentences and themes that name people the reviews name (a TA, a student)", () => {
    const withPeople = {
      names: ["Ada", "Lovelace"],
      reviews: [
        "Dr. Lovelace is great and her TA Jordan Whitfield runs helpful review sessions.",
        "My roommate Priya took it with me and we both loved the proofs.",
      ],
    };
    expect(
      cleanProfessorSummary(
        {
          summary:
            "Students say Dr. Lovelace and her TA Jordan Whitfield explain proofs patiently in office hours. Reviewers often mention clear, patient explanations of proofs.",
          themes: [
            "Jordan Whitfield runs the review sessions",
            "Studying with Priya",
            "Patient explanations",
          ],
        },
        withPeople,
      ),
    ).toEqual({
      summary: "Reviewers often mention clear, patient explanations of proofs.",
      themes: ["Patient explanations"],
    });
  });

  it("rejects long quotations and long copied runs", () => {
    const review =
      "one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty twentyone";
    expect(
      cleanProfessorSummary({ summary: `They wrote "${review}"`, themes: [] }, context),
    ).toBeNull();
    expect(
      cleanProfessorSummary(
        { summary: `Reviewers: ${review}.`, themes: [] },
        { ...context, reviews: [review] },
      ),
    ).toBeNull();
    expect(cleanProfessorSummary({ summary: "Too short.", themes: [] }, context)).toBeNull();
  });
});

describe("fetchTeacherReviews", () => {
  it("asks the RMP GraphQL endpoint for one teacher's reviews and returns plain text", async () => {
    await teacher("Katy", "Williams", 111, 12);
    vi.stubEnv("EXTERNAL_MODE", "live");
    const fetchMock = vi.fn(async (_url: string | URL | Request, init?: RequestInit) => {
      const body = JSON.parse(String(init?.body)) as {
        query: string;
        variables: { id: string; first: number };
      };
      expect(body.query).toBe(TEACHER_REVIEWS_QUERY);
      expect(body.variables).toEqual({ id: "VGVhY2hlci0111", first: 30 });
      return new Response(
        JSON.stringify({
          data: {
            node: {
              legacyId: 111,
              ratings: {
                edges: [
                  {
                    node: {
                      comment: "  <b>Great</b> teacher, very clear lectures every week.  ",
                      class: "CSC221",
                    },
                  },
                  { node: { comment: "short", class: null } },
                  { node: { comment: null, class: "CSC121" } },
                ],
              },
            },
          },
        }),
        { status: 200, headers: { "content-type": "application/json" } },
      );
    });
    vi.stubGlobal("fetch", fetchMock);
    expect(await fetchTeacherReviews(111)).toEqual([
      { course: "CSC221", text: "Great teacher, very clear lectures every week." },
    ]);
    expect(String(fetchMock.mock.calls[0]![0])).toBe("https://www.ratemyprofessors.com/graphql");
    expect(await fetchTeacherReviews(999)).toEqual([]);
    vi.unstubAllGlobals();
  });
});
