import type { Session } from "next-auth";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { withCatalogDb } from "../catalog/db";
import { aiRequest, bodyOf, errorOf, insertStudent, sessionFor, stubAuthEnv } from "./helpers";
import * as courseAbout from "@/app/api/ai/course-about/route";
import * as purge from "@/app/api/ai/admin/purge/route";
import * as report from "@/app/api/ai/report/route";
import { CourseAboutResultSchema } from "@/lib/api/ai";
import AiCache from "@/models/AiCache";
import { readShared, writeShared } from "@/server/ai/cache";
import { REPORTS_TO_HIDE, TTL_MS } from "@/server/ai/config";
import { HIDDEN_MESSAGE } from "@/server/ai/features/course-about";
import { pregenerateCourseAbout } from "@/server/ai/pregenerate";
import { mockAiRequests, resetMockAi } from "@/server/ai/mock";
import { isDefinedRoute } from "@/server/http";

/** "Report this" (3 distinct reporters hide a shared entry) and the admin purge (PLAN §6.1 W6 "Shared entries"). */

const auth = vi.hoisted(() => ({ session: null as Session | null }));
vi.mock("next-auth", async (importOriginal) => ({
  ...(await importOriginal<Record<string, unknown>>()),
  getServerSession: async () => auth.session,
}));
vi.mock("next/server", async (importOriginal) => ({
  ...(await importOriginal<Record<string, unknown>>()),
  connection: async () => undefined,
}));

withCatalogDb();

beforeEach(() => {
  stubAuthEnv();
  vi.stubEnv("AI_PROVIDER", "mock");
});

afterEach(() => {
  auth.session = null;
  resetMockAi();
});

let counter = 0;
async function signIn(options: Parameters<typeof insertStudent>[0] = {}) {
  counter += 1;
  const user = await insertStudent({ email: `student-${counter}@davidson.edu`, ...options });
  auth.session = await sessionFor(user);
  return user;
}

const CSC_221 = { termCode: "202602", courseCode: "CSC 221" };
const about = async () => {
  const res = await courseAbout.POST(aiRequest("/api/ai/course-about", CSC_221));
  return { status: res.status, body: CourseAboutResultSchema.parse(await bodyOf(res)) };
};
const reportIt = (body: unknown) => report.POST(aiRequest("/api/ai/report", body));
const purgeIt = (body: unknown) => purge.POST(aiRequest("/api/ai/admin/purge", body));

async function entryKey(): Promise<string> {
  const { body } = await about();
  if (body.kind !== "ok") throw new Error("expected ok");
  return body.data.provenance.inputHash;
}

describe("POST /api/ai/report", () => {
  it("is a defineRoute handler for verified @davidson.edu accounts", async () => {
    expect(isDefinedRoute(report.POST)).toBe(true);
    expect((await reportIt({ feature: "course-about", key: "k" })).status).toBe(401);
    await signIn({ verified: false });
    const unverified = await reportIt({ feature: "course-about", key: "k" });
    expect(unverified.status).toBe(403);
    expect((await errorOf(unverified)).code).toBe("forbidden");
    await signIn({ email: "legacy-reporter@gmail.com" });
    expect((await reportIt({ feature: "course-about", key: "k" })).status).toBe(403);
  });

  it("validates the body and answers 404 for an entry that does not exist", async () => {
    await signIn();
    for (const body of [
      { feature: "plan-suggestions", key: "k" },
      { feature: "course-about" },
      { feature: "course-about", key: "k", extra: 1 },
    ]) {
      expect((await reportIt(body)).status, JSON.stringify(body)).toBe(400);
    }
    expect((await reportIt({ feature: "course-about", key: "no-such-key" })).status).toBe(404);
  });

  it(`hides an entry after ${REPORTS_TO_HIDE} distinct reporters, for everyone, without regenerating it`, async () => {
    await signIn();
    const key = await entryKey();
    for (let i = 0; i < REPORTS_TO_HIDE - 1; i++) {
      await signIn();
      const res = await reportIt({ feature: "course-about", key, reason: `Wrong topics ${i}` });
      expect(res.status).toBe(204);
      expect((await about()).status).toBe(200);
    }
    await signIn();
    expect((await reportIt({ feature: "course-about", key })).status).toBe(204);
    const hidden = await about();
    expect(hidden.status).toBe(503);
    expect(hidden.body).toEqual({ kind: "unavailable", message: HIDDEN_MESSAGE });
    expect(mockAiRequests()).toHaveLength(1);
    const doc = await AiCache.findOne({ key }).lean();
    expect(doc).toMatchObject({ hidden: true, reports: { count: REPORTS_TO_HIDE } });
    expect(doc!.hiddenAt).toBeInstanceOf(Date);
    expect(doc!.reports!.entries.map((e) => e.reason)).toEqual([
      "Wrong topics 0",
      "Wrong topics 1",
      null,
    ]);
  });

  it("stays hidden past its lifetime: kept from the TTL monitor, never regenerated by a view or the job", async () => {
    await signIn();
    const key = await entryKey();
    const before = await AiCache.findOne({ key }).lean();
    for (let i = 0; i < REPORTS_TO_HIDE; i++) {
      await signIn();
      await reportIt({ feature: "course-about", key });
    }
    const hidden = await AiCache.findOne({ key }).lean();
    // The purge time moved a year ahead (of the real clock); the logical end did not change.
    expect(hidden!.expiresAt.getTime()).toBeGreaterThan(before!.expiresAt.getTime());
    expect(hidden!.expiresAt.getTime()).toBeGreaterThanOrEqual(Date.now() + TTL_MS.hidden - 60_000);
    expect(hidden!.validUntil).toEqual(before!.validUntil);

    // Past the entry's own 30 days: still hidden for a student, and nothing is generated over it.
    vi.stubEnv("FIXTURES_NOW", "2026-10-31T12:00:00-04:00");
    await signIn();
    expect(await about()).toEqual({
      status: 503,
      body: { kind: "unavailable", message: HIDDEN_MESSAGE },
    });
    const job = await pregenerateCourseAbout({ concurrency: 1 });
    expect(job.stoppedEarly).toBeNull();
    expect(await about()).toMatchObject({ status: 503 });
    const after = await AiCache.findOne({ key }).lean();
    expect(after).toMatchObject({
      hidden: true,
      reports: { count: REPORTS_TO_HIDE },
      validUntil: before!.validUntil,
      data: before!.data,
    });
    expect(after?.provenance?.generatedAt).toEqual(before?.provenance?.generatedAt);
    // The job generated the other courses, but not this one.
    expect(job.generated).toBeGreaterThan(1);
  });

  it("a hidden entry is never overwritten by a write, and reads return it as hidden whatever its validUntil", async () => {
    const entry = {
      inputHash: "hidden-hash",
      promptVersion: "course-about/1",
      status: "ok" as const,
      data: { summary: "Original", goodFor: [], topics: [] },
      servedModel: "claude-sonnet-5-5",
      fallbackUsed: false,
      ttlMs: 60_000,
    };
    expect(await writeShared("course-about", "hidden-hash", entry)).not.toBeNull();
    await AiCache.updateOne({ key: "hidden-hash" }, { $set: { hidden: true } });
    expect(
      await writeShared("course-about", "hidden-hash", { ...entry, data: { summary: "New" } }),
    ).toBeNull();
    vi.stubEnv("FIXTURES_NOW", "2026-12-01T12:00:00-05:00");
    const read = await readShared("course-about", "hidden-hash");
    expect(read).toMatchObject({ hidden: true, data: { summary: "Original" } });
    expect(await AiCache.countDocuments({ key: "hidden-hash" })).toBe(1);
  });

  it("counts one student once, however often they report", async () => {
    await signIn();
    const key = await entryKey();
    for (let i = 0; i < 10; i++)
      expect((await reportIt({ feature: "course-about", key })).status).toBe(204);
    const doc = await AiCache.findOne({ key }).lean();
    expect(doc).toMatchObject({ hidden: false, reports: { count: 1 } });
    expect(doc!.reports!.entries).toHaveLength(1);
    expect((await about()).status).toBe(200);
  });
});

describe("POST /api/ai/admin/purge", () => {
  it("is for ADMIN_EMAILS with a verified mailbox only", async () => {
    expect(isDefinedRoute(purge.POST)).toBe(true);
    vi.stubEnv("ADMIN_EMAILS", "owner@example.org");
    await signIn();
    expect((await purgeIt({ feature: "course-about" })).status).toBe(403);
    await signIn({ email: "owner@example.org", verified: false });
    expect((await purgeIt({ feature: "course-about" })).status).toBe(403);
  });

  it("deletes one entry or a whole feature; a purged entry is regenerated on the next view", async () => {
    vi.stubEnv("ADMIN_EMAILS", "owner@example.org");
    await signIn();
    const key = await entryKey();
    await courseAbout.POST(
      aiRequest("/api/ai/course-about", { termCode: "202602", courseCode: "CSC 121" }),
    );
    await signIn({ email: "owner@example.org" });
    const one = await purgeIt({ feature: "course-about", key });
    expect(one.status).toBe(200);
    expect(await bodyOf(one)).toEqual({ purged: 1 });
    const admin = auth.session;
    await signIn();
    expect((await about()).body).toMatchObject({ kind: "ok", cached: false });
    auth.session = admin;
    const all = await purgeIt({ feature: "course-about" });
    expect(await bodyOf(all)).toEqual({ purged: 2 });
    expect(await AiCache.countDocuments()).toBe(0);
    expect((await purgeIt({ feature: "course-about", key: "x", extra: 1 })).status).toBe(400);
  });
});
