// Career paths data for the Pathfinder-style career browsing experience

export interface CareerPath {
  id: string;
  title: string;
  icon: string; // Lucide icon name
  description: string;
  tags: string[];
  salaryRange: { min: number; max: number };
  skills: string[];
  whatYoullDo: string[];
  dayInLife: string;
  courses: Array<{
    code: string;
    name: string;
    description: string;
    bestProfessor?: string;
    difficulty: number; // 1-5
  }>;
  summerOpportunities: Array<{
    title: string;
    type: string;
    description: string;
    timing: string;
  }>;
  networking: Array<{
    role: string;
    type: string;
    description: string;
    howToConnect: string;
  }>;
}

export const CAREER_PATH_FILTERS = [
  "All",
  "High Salary",
  "Work-Life Balance",
  "Technical",
  "Analytical",
  "Leadership",
  "Creative",
] as const;

export type CareerFilter = (typeof CAREER_PATH_FILTERS)[number];

const FILTER_MAP: Record<string, CareerFilter[]> = {
  "software-engineering": ["Technical", "High Salary"],
  "data-science": ["Technical", "Analytical", "High Salary"],
  "investment-banking": ["High Salary", "Analytical", "Leadership"],
  "management-consulting": ["High Salary", "Analytical", "Leadership"],
  "product-management": ["Technical", "Leadership"],
  "medicine": ["Analytical", "High Salary"],
  "law": ["Analytical", "Leadership"],
  "marketing": ["Creative", "Leadership"],
  "research-academia": ["Analytical", "Work-Life Balance"],
  "public-policy": ["Leadership", "Work-Life Balance"],
  "entrepreneurship": ["Leadership", "Creative"],
  "journalism": ["Creative", "Work-Life Balance"],
  "environmental-science": ["Analytical", "Work-Life Balance"],
  "ux-design": ["Creative", "Technical"],
  "nonprofit": ["Leadership", "Work-Life Balance"],
  "education": ["Work-Life Balance", "Leadership"],
  "cybersecurity": ["Technical", "High Salary"],
  "financial-planning": ["Analytical", "Work-Life Balance"],
  "psychology-counseling": ["Work-Life Balance", "Analytical"],
  "international-development": ["Leadership", "Work-Life Balance"],
  "architecture-urban-planning": ["Creative", "Analytical"],
  "sports-management": ["Leadership", "Creative"],
  "healthcare-administration": ["Leadership", "High Salary"],
  "arts-museum-curation": ["Creative", "Work-Life Balance"],
};

export function filterCareerPaths(paths: CareerPath[], filter: CareerFilter): CareerPath[] {
  if (filter === "All") return paths;
  return paths.filter((p) => FILTER_MAP[p.id]?.includes(filter));
}

export const CAREER_PATHS: CareerPath[] = [
  {
    id: "software-engineering",
    title: "Software Engineering",
    icon: "Code2",
    description: "Build the technology that powers modern life — from mobile apps to cloud infrastructure and AI systems.",
    tags: ["Technical", "High Salary"],
    salaryRange: { min: 85000, max: 180000 },
    skills: ["Python", "Data Structures", "System Design", "Git", "Problem Solving"],
    whatYoullDo: [
      "Design and build software applications and systems",
      "Write clean, tested, and maintainable code",
      "Collaborate with cross-functional teams on product features",
      "Debug and optimize performance-critical systems",
      "Participate in code reviews and architectural decisions",
    ],
    dayInLife: "Your morning starts with a standup where your team syncs on priorities. You spend the first half of the day deep in code — maybe building a new API endpoint or refactoring a data pipeline. After lunch, you pair-program with a teammate to work through a tricky bug. You end the day reviewing pull requests and sketching out the architecture for next sprint's feature.",
    courses: [
      { code: "CSC 121", name: "Programming & Problem Solving", description: "Introduction to programming using Python. Covers variables, control flow, functions, and basic data structures.", bestProfessor: "Dr. Ramanujan", difficulty: 2 },
      { code: "CSC 222", name: "Data Structures", description: "Study of fundamental data structures: arrays, linked lists, trees, graphs, hash tables, and their applications.", bestProfessor: "Dr. Ramanujan", difficulty: 3 },
      { code: "CSC 231", name: "Computer Organization", description: "How computers work at the hardware level — digital logic, assembly, memory hierarchy.", bestProfessor: "Dr. Tabor", difficulty: 4 },
      { code: "CSC 321", name: "Analysis of Algorithms", description: "Algorithm design techniques and complexity analysis. Covers sorting, graph algorithms, dynamic programming.", bestProfessor: "Dr. Ramanujan", difficulty: 4 },
      { code: "MAT 150", name: "Discrete Mathematics", description: "Mathematical foundations for CS: logic, sets, combinatorics, graph theory, proof techniques.", bestProfessor: "Dr. Hossain", difficulty: 3 },
      { code: "CSC 371", name: "Software Engineering", description: "Software development methodologies, testing, version control, and team-based project work.", bestProfessor: "Dr. Webber", difficulty: 3 },
    ],
    summerOpportunities: [
      { title: "Software Engineering Internship", type: "Internship", description: "Top Davidson destinations: Microsoft, Google, Meta, Red Ventures (Charlotte), LendingTree, and startups in the Hurt Hub network. Apply through Handshake by October.", timing: "Summer after Sophomore or Junior year" },
      { title: "Hurt Hub Startup Fellowship", type: "Fellowship", description: "Work directly with a Charlotte-area startup through the Jay Hurt Hub for Innovation at Davidson. Stipend provided. Great for freshmen/sophomores.", timing: "Summer after Freshman or Sophomore year" },
      { title: "Hackathon Participation", type: "Competition", description: "Join HackDavidson (on campus), HackMIT, PennApps, or HackNC at UNC. Build projects under pressure and win prizes.", timing: "Year-round, especially fall" },
      { title: "CS Research with Davidson Faculty", type: "Research", description: "Work with Dr. Ramanujan (AI), Dr. Mendes (distributed systems), or Dr. Peck (VR) on summer research. Funded through Davidson Research Initiative.", timing: "Summer after Freshman or Sophomore year" },
    ],
    networking: [
      { role: "CS Department Faculty", type: "Faculty", description: "Build relationships with professors for research opportunities and grad school recommendations.", howToConnect: "Attend office hours regularly, especially Dr. Ramanujan and Dr. Tabor" },
      { role: "Davidson CS Alumni in Tech", type: "Alumni", description: "Connect with graduates working at major tech companies for referrals and mentorship.", howToConnect: "Use LinkedIn and Davidson alumni network; attend career fairs" },
      { role: "Career Development Center", type: "Advisor", description: "Get help with resume reviews, interview prep, and internship applications.", howToConnect: "Schedule appointments through the CDC website" },
    ],
  },
  {
    id: "data-science",
    title: "Data Science & Analytics",
    icon: "BarChart3",
    description: "Turn raw data into insights that drive decision-making across industries — from healthcare to finance to tech.",
    tags: ["Technical", "Analytical", "High Salary"],
    salaryRange: { min: 75000, max: 160000 },
    skills: ["Python", "R", "SQL", "Statistics", "Machine Learning", "Data Visualization"],
    whatYoullDo: [
      "Analyze large datasets to uncover patterns and trends",
      "Build predictive models using machine learning techniques",
      "Create dashboards and visualizations to communicate findings",
      "Design experiments and A/B tests to validate hypotheses",
      "Collaborate with stakeholders to define data-driven strategies",
    ],
    dayInLife: "You start your day reviewing overnight model performance metrics and checking data pipelines. Mid-morning, you dive into exploratory data analysis on a new customer dataset, building visualizations to spot trends. After lunch, you present findings to the product team and discuss experiment design. The afternoon is spent refining a classification model and writing documentation for your analysis.",
    courses: [
      { code: "MAT 220", name: "Probability & Statistics I", description: "Introduction to probability theory, random variables, distributions, and statistical inference.", bestProfessor: "Dr. Blake", difficulty: 3 },
      { code: "CSC 121", name: "Programming & Problem Solving", description: "Learn Python programming fundamentals — the primary language for data science.", bestProfessor: "Dr. Ramanujan", difficulty: 2 },
      { code: "MAT 150", name: "Discrete Mathematics", description: "Logic, combinatorics, and graph theory — mathematical foundations for data analysis.", bestProfessor: "Dr. Hossain", difficulty: 3 },
      { code: "ECO 255", name: "Econometrics", description: "Statistical methods applied to economic data. Regression analysis, hypothesis testing, causal inference.", bestProfessor: "Dr. Smith", difficulty: 4 },
      { code: "CSC 321", name: "Analysis of Algorithms", description: "Understand computational complexity and algorithm efficiency for large-scale data processing.", bestProfessor: "Dr. Ramanujan", difficulty: 4 },
      { code: "MAT 340", name: "Linear Algebra", description: "Vectors, matrices, transformations — essential math for machine learning and dimensionality reduction.", bestProfessor: "Dr. Hossain", difficulty: 3 },
    ],
    summerOpportunities: [
      { title: "Data Science Internship", type: "Internship", description: "Apply analytical skills at companies like Amazon, Spotify, or consulting firms.", timing: "Summer after Sophomore or Junior year" },
      { title: "Undergraduate Research Fellowship", type: "Research", description: "Work with faculty on data-driven research projects in biology, economics, or social sciences.", timing: "Summer after Freshman or Sophomore year" },
      { title: "Kaggle Competitions", type: "Competition", description: "Compete in data science challenges to build skills and portfolio projects.", timing: "Year-round" },
    ],
    networking: [
      { role: "Math & CS Faculty", type: "Faculty", description: "Connect with professors who bridge statistics and computing.", howToConnect: "Take cross-listed courses and attend department events" },
      { role: "Industry Data Scientists", type: "Professional", description: "Learn about real-world data science workflows and tools.", howToConnect: "Attend virtual meetups and LinkedIn networking events" },
    ],
  },
  {
    id: "investment-banking",
    title: "Investment Banking",
    icon: "TrendingUp",
    description: "Advise corporations on mergers, acquisitions, and capital raising — the financial engine of global business.",
    tags: ["High Salary", "Analytical", "Leadership"],
    salaryRange: { min: 100000, max: 200000 },
    skills: ["Financial Modeling", "Valuation", "Excel", "Accounting", "Communication"],
    whatYoullDo: [
      "Build detailed financial models for M&A transactions",
      "Conduct industry research and competitive analysis",
      "Prepare pitch books and presentation materials for clients",
      "Analyze company valuations using DCF, comparables, and precedent transactions",
      "Support senior bankers in deal execution and client management",
    ],
    dayInLife: "You arrive early to check market news and update your live models. The morning is spent building a DCF valuation for a potential acquisition target. After a working lunch with your deal team, you refine a pitch deck for a client meeting. Late afternoon brings a call with the client's CFO to discuss deal structure. You end the day reviewing the latest comparable transactions data.",
    courses: [
      { code: "ECO 101", name: "Principles of Economics", description: "Foundation in micro and macroeconomic theory — supply/demand, market structures, GDP.", bestProfessor: "Dr. Griffith", difficulty: 2 },
      { code: "ECO 255", name: "Econometrics", description: "Statistical methods for economic data analysis — regression, hypothesis testing.", bestProfessor: "Dr. Smith", difficulty: 4 },
      { code: "ECO 315", name: "Financial Economics", description: "Asset pricing, portfolio theory, risk management, and capital markets.", bestProfessor: "Dr. Stroup", difficulty: 4 },
      { code: "MAT 110", name: "Calculus I", description: "Limits, derivatives, integrals — the mathematical language of finance.", bestProfessor: "Dr. Blake", difficulty: 3 },
      { code: "ACC 215", name: "Financial Accounting", description: "Understanding financial statements — balance sheets, income statements, cash flow.", bestProfessor: "Dr. Palmer", difficulty: 3 },
      { code: "ECO 360", name: "Corporate Finance", description: "Capital budgeting, cost of capital, capital structure, and dividend policy.", bestProfessor: "Dr. Stroup", difficulty: 4 },
    ],
    summerOpportunities: [
      { title: "IB Summer Analyst Program", type: "Internship", description: "10-week programs at bulge bracket banks (Goldman Sachs, Morgan Stanley, JPMorgan) or boutiques (Evercore, Lazard).", timing: "Summer after Junior year (apply fall of Junior year)" },
      { title: "Sophomore Diversity Program", type: "Program", description: "Pre-internship programs at major banks for underrepresented students.", timing: "Summer after Sophomore year" },
      { title: "Davidson Finance Club", type: "Club", description: "Practice financial modeling, stock pitches, and networking with alumni in finance.", timing: "Year-round" },
    ],
    networking: [
      { role: "Davidson Alumni on Wall Street", type: "Alumni", description: "Many Davidson graduates work in banking — leverage the alumni network aggressively.", howToConnect: "Email alumni directly; use LinkedIn; attend NYC networking trips" },
      { role: "Economics Department Faculty", type: "Faculty", description: "Get strong recommendations and guidance on breaking into finance.", howToConnect: "Take advanced econ courses and build relationships early" },
      { role: "Career Development Center", type: "Advisor", description: "Resume reviews, mock interviews, and finance-specific career prep.", howToConnect: "Book appointments early in fall semester" },
    ],
  },
  {
    id: "management-consulting",
    title: "Management Consulting",
    icon: "Lightbulb",
    description: "Solve complex business problems for Fortune 500 companies — strategy, operations, and organizational design.",
    tags: ["High Salary", "Analytical", "Leadership"],
    salaryRange: { min: 90000, max: 175000 },
    skills: ["Problem Solving", "Data Analysis", "Presentation", "Strategy", "Leadership"],
    whatYoullDo: [
      "Structure ambiguous business problems into solvable frameworks",
      "Conduct market research and competitive benchmarking",
      "Analyze data to develop strategic recommendations",
      "Present findings to C-suite executives",
      "Lead workstreams and manage junior team members",
    ],
    dayInLife: "Your week alternates between client site (Mon-Thu) and your home office (Fri). On-site days start with a team check-in, then you spend the morning analyzing customer survey data. After lunch with the client's VP of Strategy, you build slides synthesizing your findings. The afternoon is a workshop with client stakeholders to pressure-test your recommendations.",
    courses: [
      { code: "ECO 101", name: "Principles of Economics", description: "Microeconomic and macroeconomic fundamentals for business analysis.", bestProfessor: "Dr. Griffith", difficulty: 2 },
      { code: "MAT 220", name: "Probability & Statistics I", description: "Statistical analysis skills essential for data-driven consulting.", bestProfessor: "Dr. Blake", difficulty: 3 },
      { code: "PSY 100", name: "Introduction to Psychology", description: "Understanding human behavior and decision-making — key for organizational consulting.", bestProfessor: "Dr. Bagwell", difficulty: 2 },
      { code: "COM 210", name: "Public Speaking", description: "Develop clear, persuasive communication skills for client presentations.", bestProfessor: "Dr. Martinez", difficulty: 2 },
      { code: "PHI 220", name: "Ethics", description: "Frameworks for ethical reasoning — critical for advising organizations responsibly.", bestProfessor: "Dr. McKeever", difficulty: 3 },
      { code: "ECO 255", name: "Econometrics", description: "Quantitative analysis and regression modeling for business insights.", bestProfessor: "Dr. Smith", difficulty: 4 },
    ],
    summerOpportunities: [
      { title: "Consulting Summer Analyst", type: "Internship", description: "Intern at MBB (McKinsey, Bain, BCG) or other top firms (Deloitte, Accenture, LEK).", timing: "Summer after Junior year" },
      { title: "Case Competition", type: "Competition", description: "Participate in case competitions to build analytical and presentation skills.", timing: "Fall and Spring semesters" },
      { title: "Non-profit Consulting", type: "Project", description: "Gain real consulting experience by advising local nonprofits on strategy.", timing: "Any summer" },
    ],
    networking: [
      { role: "Davidson Alumni in Consulting", type: "Alumni", description: "Davidson punches above its weight in MBB placements — use the network.", howToConnect: "Request coffee chats via LinkedIn; attend info sessions" },
      { role: "Career Center Consulting Prep", type: "Advisor", description: "Case interview practice, resume workshops, and firm-specific advice.", howToConnect: "Join the consulting prep group early in sophomore year" },
    ],
  },
  {
    id: "product-management",
    title: "Product Management",
    icon: "Layers",
    description: "Define what gets built and why — lead the intersection of business, design, and engineering at tech companies.",
    tags: ["Technical", "Leadership"],
    salaryRange: { min: 90000, max: 170000 },
    skills: ["Strategy", "User Research", "Data Analysis", "Communication", "Technical Fluency"],
    whatYoullDo: [
      "Define product vision and roadmap based on user needs and business goals",
      "Write product requirements and user stories for engineering teams",
      "Analyze user data and feedback to prioritize features",
      "Coordinate cross-functional teams (engineering, design, marketing)",
      "Run experiments and iterate based on metrics",
    ],
    dayInLife: "You start with metrics review — checking overnight usage data and experiment results. Morning standup with your engineering team covers sprint progress. You spend mid-morning interviewing users to validate a new feature concept. After lunch, you work with design on wireframes, then sync with marketing on the upcoming launch. The day ends with a roadmap planning session.",
    courses: [
      { code: "CSC 121", name: "Programming & Problem Solving", description: "Enough technical depth to collaborate effectively with engineers.", bestProfessor: "Dr. Ramanujan", difficulty: 2 },
      { code: "ECO 101", name: "Principles of Economics", description: "Business fundamentals and market dynamics for product strategy.", bestProfessor: "Dr. Griffith", difficulty: 2 },
      { code: "PSY 100", name: "Introduction to Psychology", description: "Understand user behavior and cognitive biases for better product design.", bestProfessor: "Dr. Bagwell", difficulty: 2 },
      { code: "MAT 220", name: "Probability & Statistics I", description: "Data analysis skills for metrics-driven product decisions.", bestProfessor: "Dr. Blake", difficulty: 3 },
      { code: "COM 210", name: "Public Speaking", description: "Present product vision clearly to stakeholders and executives.", bestProfessor: "Dr. Martinez", difficulty: 2 },
    ],
    summerOpportunities: [
      { title: "APM Program", type: "Internship", description: "Associate Product Manager internships at Google, Meta, Microsoft, or Uber.", timing: "Summer after Junior year" },
      { title: "Startup Internship", type: "Internship", description: "Wear multiple hats at a startup — closer to the product and faster iteration.", timing: "Any summer" },
      { title: "Build a Side Project", type: "Project", description: "Ship a real product (app, website, tool) to demonstrate product thinking.", timing: "Any time" },
    ],
    networking: [
      { role: "Tech Alumni in PM Roles", type: "Alumni", description: "Learn about different PM career paths and get referrals.", howToConnect: "LinkedIn outreach with specific, thoughtful questions" },
      { role: "CS & Design Faculty", type: "Faculty", description: "Bridge technical and creative perspectives.", howToConnect: "Take courses that blend CS with design or business" },
    ],
  },
  {
    id: "medicine",
    title: "Healthcare & Medicine",
    icon: "Heart",
    description: "Diagnose, treat, and prevent disease — from clinical practice to medical research and public health.",
    tags: ["Analytical", "High Salary"],
    salaryRange: { min: 60000, max: 300000 },
    skills: ["Biology", "Chemistry", "Patient Care", "Critical Thinking", "Research Methods"],
    whatYoullDo: [
      "Diagnose and treat patients with evidence-based medicine",
      "Conduct clinical research to advance medical knowledge",
      "Collaborate with interdisciplinary healthcare teams",
      "Communicate complex medical information to patients and families",
      "Stay current with medical literature and continuing education",
    ],
    dayInLife: "Residency days start early with patient rounds at 6 AM, reviewing overnight changes. Morning clinic hours involve seeing patients, ordering labs, and consulting with specialists. You attend a noon conference on the latest treatment protocols. The afternoon is spent in the OR or following up on test results. You end with chart notes and preparing for tomorrow's cases.",
    courses: [
      { code: "BIO 111", name: "Introductory Biology I", description: "Cell biology, genetics, and molecular biology — the foundation of medical science.", bestProfessor: "Dr. Johnson", difficulty: 3 },
      { code: "BIO 112", name: "Introductory Biology II", description: "Ecology, evolution, and organismal biology.", bestProfessor: "Dr. Johnson", difficulty: 3 },
      { code: "CHE 115", name: "General Chemistry I", description: "Atomic structure, bonding, stoichiometry — essential for understanding pharmacology.", bestProfessor: "Dr. Snyder", difficulty: 3 },
      { code: "CHE 240", name: "Organic Chemistry I", description: "Carbon chemistry and reaction mechanisms — the gateway to biochemistry.", bestProfessor: "Dr. Snyder", difficulty: 5 },
      { code: "BIO 306", name: "Biochemistry", description: "Protein structure, enzyme kinetics, metabolic pathways.", bestProfessor: "Dr. Rodriguez", difficulty: 4 },
      { code: "PSY 100", name: "Introduction to Psychology", description: "Understanding the psychological dimensions of patient care.", bestProfessor: "Dr. Bagwell", difficulty: 2 },
    ],
    summerOpportunities: [
      { title: "Clinical Shadowing", type: "Experience", description: "Shadow physicians in various specialties to explore interests and build clinical exposure.", timing: "Summer after Freshman year" },
      { title: "Biomedical Research", type: "Research", description: "Work in a research lab at Davidson or an academic medical center.", timing: "Summer after Sophomore year" },
      { title: "Medical Mission Trip", type: "Service", description: "Gain global health experience while serving underserved communities.", timing: "Any summer or winter break" },
      { title: "MCAT Preparation", type: "Preparation", description: "Dedicate time to MCAT study — most students take it summer after Junior year.", timing: "Summer after Junior year" },
    ],
    networking: [
      { role: "Pre-Health Advisor", type: "Advisor", description: "Guidance on pre-med track, med school applications, and gap year planning.", howToConnect: "Schedule regular meetings starting freshman year" },
      { role: "Davidson Pre-Med Alumni", type: "Alumni", description: "Learn about different medical schools and specialties from Davidson graduates.", howToConnect: "Pre-health alumni panels and LinkedIn outreach" },
      { role: "Biology & Chemistry Faculty", type: "Faculty", description: "Strong letters of recommendation and research opportunities.", howToConnect: "Excel in courses and seek out lab opportunities" },
    ],
  },
  {
    id: "law",
    title: "Law",
    icon: "Scale",
    description: "Advocate, negotiate, and shape policy — from corporate law to public interest litigation and government service.",
    tags: ["Analytical", "Leadership"],
    salaryRange: { min: 70000, max: 190000 },
    skills: ["Legal Writing", "Critical Analysis", "Research", "Public Speaking", "Negotiation"],
    whatYoullDo: [
      "Research legal precedents and analyze case law",
      "Draft legal documents, briefs, and contracts",
      "Represent clients in negotiations, mediations, and court proceedings",
      "Advise organizations on legal compliance and risk management",
      "Develop legal strategies for complex disputes",
    ],
    dayInLife: "Your morning begins with reviewing case files and drafting a motion. You spend mid-morning in a client meeting discussing litigation strategy. After lunch, you research precedent cases in Westlaw for a brief due next week. The afternoon includes a deposition and a call with opposing counsel to discuss settlement terms. You end the day reviewing contracts for a corporate client.",
    courses: [
      { code: "POL 101", name: "American Government", description: "The structure and function of U.S. government — constitutional law foundations.", bestProfessor: "Dr. Roberts", difficulty: 2 },
      { code: "PHI 220", name: "Ethics", description: "Moral reasoning frameworks essential for legal practice.", bestProfessor: "Dr. McKeever", difficulty: 3 },
      { code: "ENG 270", name: "Expository Writing", description: "Persuasive writing and argumentation — the core skill of legal practice.", bestProfessor: "Dr. Rippeon", difficulty: 3 },
      { code: "POL 315", name: "Constitutional Law", description: "Deep dive into constitutional interpretation and landmark Supreme Court cases.", bestProfessor: "Dr. Roberts", difficulty: 4 },
      { code: "HIS 200", name: "American History", description: "Historical context for understanding legal evolution and social justice.", bestProfessor: "Dr. Aldridge", difficulty: 2 },
      { code: "COM 210", name: "Public Speaking", description: "Oral advocacy skills for courtroom and client presentations.", bestProfessor: "Dr. Martinez", difficulty: 2 },
    ],
    summerOpportunities: [
      { title: "Law Firm Internship", type: "Internship", description: "Work at a law firm to experience legal practice firsthand.", timing: "Summer after Sophomore or Junior year" },
      { title: "Government Internship", type: "Internship", description: "Intern at the DOJ, state attorney general, or a congressional office.", timing: "Summer after Sophomore year" },
      { title: "Mock Trial Competition", type: "Competition", description: "Develop trial advocacy skills through competitive mock trial.", timing: "Year-round" },
      { title: "LSAT Preparation", type: "Preparation", description: "Study for the LSAT — most students take it junior or senior year.", timing: "Summer after Junior year" },
    ],
    networking: [
      { role: "Pre-Law Advisor", type: "Advisor", description: "Guidance on law school applications and career path options.", howToConnect: "Schedule meetings with the pre-law advisor early" },
      { role: "Davidson Alumni Attorneys", type: "Alumni", description: "Learn about different legal specialties and get application advice.", howToConnect: "Alumni networking events and LinkedIn" },
      { role: "Political Science Faculty", type: "Faculty", description: "Strong recommendations and mentorship in legal thinking.", howToConnect: "Take advanced courses in constitutional law and political theory" },
    ],
  },
  {
    id: "marketing",
    title: "Marketing & Communications",
    icon: "Megaphone",
    description: "Shape how brands connect with audiences through strategy, storytelling, data, and creative campaigns.",
    tags: ["Creative", "Leadership"],
    salaryRange: { min: 50000, max: 120000 },
    skills: ["Storytelling", "Analytics", "Social Media", "Brand Strategy", "Content Creation"],
    whatYoullDo: [
      "Develop marketing strategies and campaign plans",
      "Create compelling content across digital and traditional channels",
      "Analyze campaign performance and optimize based on data",
      "Manage brand identity and messaging consistency",
      "Collaborate with creative teams and external agencies",
    ],
    dayInLife: "Your morning starts with checking campaign analytics and social media engagement. You join a creative brainstorm for an upcoming product launch. Mid-morning, you review copy and design assets for a digital ad campaign. After lunch, you analyze A/B test results and adjust targeting. The afternoon is spent planning content for next month and meeting with an influencer partner.",
    courses: [
      { code: "COM 210", name: "Public Speaking", description: "Clear, persuasive communication — the foundation of marketing.", bestProfessor: "Dr. Martinez", difficulty: 2 },
      { code: "PSY 100", name: "Introduction to Psychology", description: "Consumer behavior and decision-making psychology.", bestProfessor: "Dr. Bagwell", difficulty: 2 },
      { code: "ECO 101", name: "Principles of Economics", description: "Market dynamics and consumer theory.", bestProfessor: "Dr. Griffith", difficulty: 2 },
      { code: "ENG 220", name: "Creative Writing", description: "Storytelling and narrative skills for compelling brand content.", bestProfessor: "Dr. Rippeon", difficulty: 2 },
      { code: "ART 120", name: "Visual Design", description: "Principles of visual communication and design thinking.", bestProfessor: "Prof. St. Clair", difficulty: 2 },
      { code: "MAT 220", name: "Probability & Statistics I", description: "Data literacy for measuring marketing effectiveness.", bestProfessor: "Dr. Blake", difficulty: 3 },
    ],
    summerOpportunities: [
      { title: "Marketing Internship", type: "Internship", description: "Work at an agency, brand, or tech company marketing team.", timing: "Summer after Sophomore or Junior year" },
      { title: "Content Creation", type: "Project", description: "Build a personal brand or portfolio through blogging, social media, or video.", timing: "Year-round" },
      { title: "Brand Strategy Case Competition", type: "Competition", description: "Develop a marketing strategy for a real brand challenge.", timing: "Fall or Spring semester" },
    ],
    networking: [
      { role: "Communications Faculty", type: "Faculty", description: "Mentorship in storytelling and media strategy.", howToConnect: "Take communication studies courses and build relationships" },
      { role: "Marketing Alumni", type: "Alumni", description: "Learn about agency vs. in-house vs. startup marketing careers.", howToConnect: "LinkedIn outreach and alumni career panels" },
    ],
  },
  {
    id: "research-academia",
    title: "Research & Academia",
    icon: "Microscope",
    description: "Push the boundaries of human knowledge through original research, teaching, and scholarly publication.",
    tags: ["Analytical", "Work-Life Balance"],
    salaryRange: { min: 55000, max: 130000 },
    skills: ["Research Methods", "Writing", "Critical Analysis", "Teaching", "Grant Writing"],
    whatYoullDo: [
      "Design and conduct original research studies",
      "Publish findings in peer-reviewed journals",
      "Teach courses and mentor students",
      "Apply for grants to fund research programs",
      "Present at academic conferences worldwide",
    ],
    dayInLife: "Your morning starts with writing — working on a journal article or grant proposal. Late morning, you teach an undergraduate seminar. After lunch, you meet with graduate students to discuss their research progress. The afternoon is spent in the lab or analyzing data. You end with reviewing a paper for a journal and preparing for tomorrow's lecture.",
    courses: [
      { code: "MAT 220", name: "Probability & Statistics I", description: "Research methodology and statistical analysis fundamentals.", bestProfessor: "Dr. Blake", difficulty: 3 },
      { code: "PHI 220", name: "Ethics", description: "Research ethics and responsible scholarship.", bestProfessor: "Dr. McKeever", difficulty: 3 },
      { code: "ENG 270", name: "Expository Writing", description: "Academic writing skills for publications and grant proposals.", bestProfessor: "Dr. Rippeon", difficulty: 3 },
    ],
    summerOpportunities: [
      { title: "Faculty Research Assistant", type: "Research", description: "Work directly with Davidson faculty on publishable research.", timing: "Summer after Freshman or Sophomore year" },
      { title: "REU Program", type: "Research", description: "NSF-funded Research Experience for Undergraduates at major universities.", timing: "Summer after Sophomore or Junior year" },
      { title: "Conference Presentation", type: "Experience", description: "Present your research at regional or national academic conferences.", timing: "Junior or Senior year" },
    ],
    networking: [
      { role: "Faculty Mentors", type: "Faculty", description: "Your most important relationships — they'll guide your path to grad school.", howToConnect: "Start research early and maintain long-term mentorship" },
      { role: "Graduate School Alumni", type: "Alumni", description: "Learn about PhD programs and the academic job market.", howToConnect: "Faculty can connect you with their former students" },
    ],
  },
  {
    id: "public-policy",
    title: "Government & Public Policy",
    icon: "Landmark",
    description: "Shape the rules and systems that govern society — from local government to federal policy to international relations.",
    tags: ["Leadership", "Work-Life Balance"],
    salaryRange: { min: 50000, max: 120000 },
    skills: ["Policy Analysis", "Research", "Writing", "Public Speaking", "Data Analysis"],
    whatYoullDo: [
      "Research and analyze policy proposals and their potential impact",
      "Draft legislation, regulations, and policy briefs",
      "Engage with stakeholders and constituents",
      "Manage government programs and budgets",
      "Advocate for policy changes through data and persuasion",
    ],
    dayInLife: "Your morning starts with a briefing on the latest policy developments. You spend the first half reviewing a draft regulation and preparing talking points for your director. After lunch, you attend a committee hearing and take notes on stakeholder testimony. The afternoon is spent analyzing the budgetary impact of a proposed amendment. You end with a call to a state agency partner.",
    courses: [
      { code: "POL 101", name: "American Government", description: "How U.S. government works — the foundation of policy work.", bestProfessor: "Dr. Roberts", difficulty: 2 },
      { code: "ECO 101", name: "Principles of Economics", description: "Economic analysis for policy evaluation.", bestProfessor: "Dr. Griffith", difficulty: 2 },
      { code: "POL 250", name: "International Relations", description: "Global politics and international policy frameworks.", bestProfessor: "Dr. Roberts", difficulty: 3 },
      { code: "SOC 101", name: "Introduction to Sociology", description: "Understanding social structures that policy aims to address.", bestProfessor: "Dr. Rivera", difficulty: 2 },
      { code: "MAT 220", name: "Probability & Statistics I", description: "Data analysis for evidence-based policymaking.", bestProfessor: "Dr. Blake", difficulty: 3 },
    ],
    summerOpportunities: [
      { title: "Congressional Internship", type: "Internship", description: "Work in a congressional office on Capitol Hill.", timing: "Summer after Sophomore or Junior year" },
      { title: "Think Tank Research", type: "Research", description: "Contribute to policy research at organizations like Brookings or RAND.", timing: "Summer after Junior year" },
      { title: "Local Government Fellowship", type: "Fellowship", description: "Work with local government on community issues.", timing: "Any summer" },
    ],
    networking: [
      { role: "Political Science Faculty", type: "Faculty", description: "Mentorship in policy analysis and connections to policy networks.", howToConnect: "Take advanced political science courses" },
      { role: "Government Alumni", type: "Alumni", description: "Davidson alumni in government and policy roles.", howToConnect: "D.C. networking events and alumni panels" },
    ],
  },
  {
    id: "entrepreneurship",
    title: "Entrepreneurship",
    icon: "Rocket",
    description: "Launch and scale your own ventures — from tech startups to social enterprises to small businesses.",
    tags: ["Leadership", "Creative"],
    salaryRange: { min: 0, max: 200000 },
    skills: ["Business Strategy", "Sales", "Leadership", "Fundraising", "Product Development"],
    whatYoullDo: [
      "Identify market opportunities and validate business ideas",
      "Build minimum viable products and iterate based on feedback",
      "Pitch to investors and secure funding",
      "Recruit and lead a founding team",
      "Manage operations, finances, and growth strategy",
    ],
    dayInLife: "No two days are the same. You might start the morning reviewing user metrics, then hop on a call with a potential investor. Mid-day you're sketching out a new feature with your co-founder. After lunch, you're networking at a startup event, then back to writing copy for your landing page. The evening is spent catching up on emails and planning tomorrow's priorities.",
    courses: [
      { code: "ECO 101", name: "Principles of Economics", description: "Market fundamentals and business economics.", bestProfessor: "Dr. Griffith", difficulty: 2 },
      { code: "CSC 121", name: "Programming & Problem Solving", description: "Technical literacy to build or manage technical products.", bestProfessor: "Dr. Ramanujan", difficulty: 2 },
      { code: "COM 210", name: "Public Speaking", description: "Pitching and presenting to investors and customers.", bestProfessor: "Dr. Martinez", difficulty: 2 },
      { code: "PSY 100", name: "Introduction to Psychology", description: "Understanding customers, team dynamics, and negotiation.", bestProfessor: "Dr. Bagwell", difficulty: 2 },
      { code: "ACC 215", name: "Financial Accounting", description: "Reading financial statements and managing company finances.", bestProfessor: "Dr. Palmer", difficulty: 3 },
    ],
    summerOpportunities: [
      { title: "Startup Accelerator", type: "Program", description: "Join programs like Y Combinator, Techstars, or university-affiliated accelerators.", timing: "Summer after Junior year" },
      { title: "Build Your Startup", type: "Project", description: "Use the summer to build and launch your own product.", timing: "Any summer" },
      { title: "Startup Internship", type: "Internship", description: "Work at an early-stage startup to learn how they operate.", timing: "Any summer" },
    ],
    networking: [
      { role: "Entrepreneurship Faculty", type: "Faculty", description: "Guidance on business planning and connecting with the startup ecosystem.", howToConnect: "Take business-related courses and pitch your ideas" },
      { role: "Founder Alumni", type: "Alumni", description: "Learn from Davidson graduates who've built companies.", howToConnect: "Entrepreneurship events and alumni introductions" },
    ],
  },
  {
    id: "ux-design",
    title: "UX Design",
    icon: "Palette",
    description: "Design intuitive, beautiful digital experiences — combining user research, interaction design, and visual craft.",
    tags: ["Creative", "Technical"],
    salaryRange: { min: 70000, max: 140000 },
    skills: ["User Research", "Prototyping", "Visual Design", "Usability Testing", "Figma"],
    whatYoullDo: [
      "Conduct user research to understand needs and pain points",
      "Create wireframes, prototypes, and high-fidelity designs",
      "Run usability tests and iterate on designs",
      "Define design systems and interaction patterns",
      "Collaborate with engineers to implement designs",
    ],
    dayInLife: "Your morning starts with a user interview — observing how someone interacts with your product prototype. You spend mid-morning synthesizing research notes and updating your findings deck. After lunch, you iterate on wireframes in Figma based on feedback. The afternoon involves a design critique with your team and a handoff meeting with engineers. You end the day exploring design inspiration.",
    courses: [
      { code: "ART 120", name: "Visual Design", description: "Foundational design principles — color, typography, layout, composition.", bestProfessor: "Prof. St. Clair", difficulty: 2 },
      { code: "PSY 100", name: "Introduction to Psychology", description: "Cognitive psychology and human behavior for user-centered design.", bestProfessor: "Dr. Bagwell", difficulty: 2 },
      { code: "CSC 121", name: "Programming & Problem Solving", description: "Enough code to prototype and communicate with engineers.", bestProfessor: "Dr. Ramanujan", difficulty: 2 },
      { code: "COM 210", name: "Public Speaking", description: "Presenting and defending design decisions to stakeholders.", bestProfessor: "Dr. Martinez", difficulty: 2 },
      { code: "ANT 200", name: "Ethnographic Methods", description: "Qualitative research methods for understanding users in context.", bestProfessor: "Dr. Bowles", difficulty: 3 },
    ],
    summerOpportunities: [
      { title: "UX Design Internship", type: "Internship", description: "Design intern at a tech company, agency, or startup.", timing: "Summer after Sophomore or Junior year" },
      { title: "Portfolio Project", type: "Project", description: "Build a UX portfolio with 3-4 complete case studies.", timing: "Junior year onward" },
      { title: "Design Sprint", type: "Workshop", description: "Participate in design sprints or workshops to sharpen skills.", timing: "Year-round" },
    ],
    networking: [
      { role: "Art & Digital Studies Faculty", type: "Faculty", description: "Mentorship in design thinking and creative process.", howToConnect: "Take art and digital studies courses" },
      { role: "UX Designers in Industry", type: "Professional", description: "Learn about UX career paths and portfolio expectations.", howToConnect: "Attend UXPA events, Dribbble meetups, and LinkedIn" },
    ],
  },
  {
    id: "nonprofit",
    title: "Nonprofit & Social Impact",
    icon: "HeartHandshake",
    description: "Drive meaningful change through mission-driven organizations focused on education, health, equity, and the environment.",
    tags: ["Leadership", "Work-Life Balance"],
    salaryRange: { min: 40000, max: 90000 },
    skills: ["Grant Writing", "Program Management", "Fundraising", "Community Engagement", "Leadership"],
    whatYoullDo: [
      "Design and manage programs that serve communities",
      "Write grants and fundraise to sustain operations",
      "Build partnerships with government and private sector",
      "Measure and report on program impact",
      "Advocate for policy change and community needs",
    ],
    dayInLife: "Your morning starts with a team meeting to review program metrics. You spend mid-morning drafting a grant proposal for a foundation. After lunch, you visit a program site and meet with community members. The afternoon is spent preparing a board presentation and coordinating with volunteers. You end with a networking call with a potential corporate partner.",
    courses: [
      { code: "SOC 101", name: "Introduction to Sociology", description: "Understanding social structures, inequality, and community dynamics.", bestProfessor: "Dr. Rivera", difficulty: 2 },
      { code: "ECO 101", name: "Principles of Economics", description: "Economic analysis for nonprofit sustainability.", bestProfessor: "Dr. Griffith", difficulty: 2 },
      { code: "ENG 270", name: "Expository Writing", description: "Clear writing for grants, reports, and communications.", bestProfessor: "Dr. Rippeon", difficulty: 3 },
      { code: "POL 101", name: "American Government", description: "Government structures and how nonprofits influence policy.", bestProfessor: "Dr. Roberts", difficulty: 2 },
      { code: "PSY 100", name: "Introduction to Psychology", description: "Understanding human motivation and community behavior.", bestProfessor: "Dr. Bagwell", difficulty: 2 },
    ],
    summerOpportunities: [
      { title: "Nonprofit Internship", type: "Internship", description: "Work at organizations like Teach for America, Habitat for Humanity, or local nonprofits.", timing: "Any summer" },
      { title: "Service Learning", type: "Service", description: "Combine community service with academic reflection.", timing: "Year-round" },
      { title: "Social Innovation Fellowship", type: "Fellowship", description: "Design and pilot a social impact project.", timing: "Summer after Sophomore or Junior year" },
    ],
    networking: [
      { role: "Community Engagement Staff", type: "Advisor", description: "Davidson's community engagement office connects students with nonprofits.", howToConnect: "Visit the community engagement office" },
      { role: "Nonprofit Alumni", type: "Alumni", description: "Davidson alumni leading nonprofit organizations.", howToConnect: "Alumni panels and service learning networks" },
    ],
  },
  {
    id: "education",
    title: "Education",
    icon: "GraduationCap",
    description: "Shape the next generation through teaching, curriculum design, and educational leadership at all levels.",
    tags: ["Work-Life Balance", "Leadership"],
    salaryRange: { min: 40000, max: 85000 },
    skills: ["Teaching", "Curriculum Design", "Communication", "Assessment", "Mentorship"],
    whatYoullDo: [
      "Design engaging lesson plans and curriculum",
      "Teach and mentor students of all backgrounds",
      "Assess learning outcomes and adapt instruction",
      "Collaborate with colleagues on school-wide initiatives",
      "Engage with families and community stakeholders",
    ],
    dayInLife: "Your day starts early preparing materials for your first class. You teach three classes in the morning, each with different activities and discussion formats. Lunch is spent tutoring a struggling student. The afternoon includes a faculty meeting, grading, and planning tomorrow's lessons. You end the day coaching the debate team.",
    courses: [
      { code: "EDU 200", name: "Foundations of Education", description: "History, philosophy, and sociology of education in America.", bestProfessor: "Dr. Nelson", difficulty: 2 },
      { code: "PSY 100", name: "Introduction to Psychology", description: "Child development and learning psychology.", bestProfessor: "Dr. Bagwell", difficulty: 2 },
      { code: "PSY 230", name: "Developmental Psychology", description: "How children and adolescents develop cognitively and socially.", bestProfessor: "Dr. Bagwell", difficulty: 3 },
      { code: "COM 210", name: "Public Speaking", description: "Classroom communication and presentation skills.", bestProfessor: "Dr. Martinez", difficulty: 2 },
      { code: "SOC 101", name: "Introduction to Sociology", description: "Understanding educational equity and social context.", bestProfessor: "Dr. Rivera", difficulty: 2 },
    ],
    summerOpportunities: [
      { title: "Teaching Fellowship", type: "Fellowship", description: "Summer teaching programs in underserved schools.", timing: "Summer after Sophomore or Junior year" },
      { title: "Tutoring Program", type: "Service", description: "Tutor local students and develop mentoring relationships.", timing: "Year-round" },
      { title: "Education Research", type: "Research", description: "Research with education studies faculty on teaching methods or policy.", timing: "Summer after Junior year" },
    ],
    networking: [
      { role: "Education Studies Faculty", type: "Faculty", description: "Mentorship and student teaching placement support.", howToConnect: "Take education studies courses and join the education club" },
      { role: "Teacher Alumni", type: "Alumni", description: "Davidson alumni in teaching and educational leadership.", howToConnect: "Alumni panels and Teach for America network" },
    ],
  },
  {
    id: "journalism",
    title: "Media & Journalism",
    icon: "Newspaper",
    description: "Inform the public through investigative reporting, multimedia storytelling, and digital media production.",
    tags: ["Creative", "Work-Life Balance"],
    salaryRange: { min: 40000, max: 95000 },
    skills: ["Writing", "Reporting", "Multimedia Production", "Critical Thinking", "Ethics"],
    whatYoullDo: [
      "Research and report on stories of public interest",
      "Conduct interviews and verify information from multiple sources",
      "Write articles, produce videos, and create multimedia content",
      "Meet deadlines and work under pressure",
      "Develop expertise in a beat (politics, tech, health, etc.)",
    ],
    dayInLife: "Your morning starts with a news meeting where editors discuss the day's stories. You spend mid-morning making calls to sources and reviewing documents for an investigative piece. After lunch, you conduct an interview and begin drafting your article. The afternoon is a race to file before deadline — writing, editing, and adding multimedia. You end with a quick social media post to promote the story.",
    courses: [
      { code: "ENG 220", name: "Creative Writing", description: "Narrative storytelling and developing your writing voice.", bestProfessor: "Dr. Rippeon", difficulty: 2 },
      { code: "COM 210", name: "Public Speaking", description: "Interview techniques and on-camera communication.", bestProfessor: "Dr. Martinez", difficulty: 2 },
      { code: "POL 101", name: "American Government", description: "Understanding government for political reporting.", bestProfessor: "Dr. Roberts", difficulty: 2 },
      { code: "PHI 220", name: "Ethics", description: "Media ethics and responsible journalism.", bestProfessor: "Dr. McKeever", difficulty: 3 },
      { code: "DIG 200", name: "Digital Media Production", description: "Video, audio, and multimedia production skills.", bestProfessor: "Prof. Mundy", difficulty: 2 },
    ],
    summerOpportunities: [
      { title: "Newsroom Internship", type: "Internship", description: "Work at a newspaper, magazine, or digital media outlet.", timing: "Summer after Sophomore or Junior year" },
      { title: "Campus Publication", type: "Experience", description: "Write for The Davidsonian or contribute to campus media.", timing: "Year-round" },
      { title: "Multimedia Portfolio", type: "Project", description: "Build a portfolio of published clips, videos, and multimedia work.", timing: "Junior year onward" },
    ],
    networking: [
      { role: "Communication Studies Faculty", type: "Faculty", description: "Mentorship in media production and journalism ethics.", howToConnect: "Take communication and writing courses" },
      { role: "Journalist Alumni", type: "Alumni", description: "Davidson graduates working in media and journalism.", howToConnect: "Alumni panels and journalism organization events" },
    ],
  },
  {
    id: "environmental-science",
    title: "Environmental Science",
    icon: "TreePine",
    description: "Protect and restore the natural world through research, conservation, policy, and sustainable technology.",
    tags: ["Analytical", "Work-Life Balance"],
    salaryRange: { min: 50000, max: 110000 },
    skills: ["Field Research", "Data Analysis", "GIS", "Policy Writing", "Environmental Law"],
    whatYoullDo: [
      "Conduct field research and environmental monitoring",
      "Analyze environmental data and model ecological systems",
      "Develop sustainability plans for organizations",
      "Advise on environmental policy and regulatory compliance",
      "Communicate science to policymakers and the public",
    ],
    dayInLife: "Your morning starts with a field visit to a wetland restoration site, collecting water samples and monitoring species. Back at the office, you input data and update your GIS maps. After lunch, you analyze soil contamination data for an environmental impact assessment. The afternoon involves a meeting with a state agency on new regulations. You end the day drafting a section of an environmental report.",
    courses: [
      { code: "ENV 101", name: "Environmental Science", description: "Interdisciplinary introduction to environmental systems and challenges.", bestProfessor: "Dr. Chillag", difficulty: 2 },
      { code: "BIO 111", name: "Introductory Biology I", description: "Ecological foundations and biodiversity.", bestProfessor: "Dr. Johnson", difficulty: 3 },
      { code: "CHE 115", name: "General Chemistry I", description: "Chemical processes in environmental systems.", bestProfessor: "Dr. Snyder", difficulty: 3 },
      { code: "MAT 220", name: "Probability & Statistics I", description: "Statistical methods for environmental data analysis.", bestProfessor: "Dr. Blake", difficulty: 3 },
      { code: "POL 250", name: "International Relations", description: "Global environmental policy and climate agreements.", bestProfessor: "Dr. Roberts", difficulty: 3 },
    ],
    summerOpportunities: [
      { title: "Environmental Research", type: "Research", description: "Field research with Davidson faculty or at an environmental research station.", timing: "Summer after Sophomore year" },
      { title: "Conservation Internship", type: "Internship", description: "Work with organizations like The Nature Conservancy, EPA, or state agencies.", timing: "Summer after Junior year" },
      { title: "Sustainability Project", type: "Project", description: "Lead a sustainability initiative on campus or in the community.", timing: "Any time" },
    ],
    networking: [
      { role: "Environmental Studies Faculty", type: "Faculty", description: "Research opportunities and connections to environmental organizations.", howToConnect: "Take ENV courses and participate in field trips" },
      { role: "Environmental Alumni", type: "Alumni", description: "Davidson alumni in conservation, policy, and sustainability roles.", howToConnect: "Alumni network and environmental organization events" },
    ],
  },
  {
    id: "cybersecurity",
    title: "Cybersecurity",
    icon: "Shield",
    description: "Protect organizations from cyber threats by defending networks, analyzing vulnerabilities, and building secure systems.",
    tags: ["Technical", "High Salary"],
    salaryRange: { min: 80000, max: 165000 },
    skills: ["Network Security", "Python", "Risk Analysis", "Cryptography", "Incident Response"],
    whatYoullDo: [
      "Monitor networks and systems for security breaches",
      "Conduct penetration testing and vulnerability assessments",
      "Design and implement security protocols and architectures",
      "Respond to and investigate security incidents",
      "Develop security policies and train employees on best practices",
    ],
    dayInLife: "Your morning starts with reviewing overnight security alerts and threat intelligence feeds. You spend mid-morning conducting a vulnerability scan on a new application before deployment. After lunch, you lead a tabletop exercise simulating a ransomware attack. The afternoon involves analyzing logs from a suspicious login attempt and writing up your findings. You end the day updating firewall rules and patching a newly disclosed vulnerability.",
    courses: [
      { code: "CSC 121", name: "Programming & Problem Solving", description: "Python fundamentals for writing security scripts and automation tools.", bestProfessor: "Dr. Ramanujan", difficulty: 2 },
      { code: "CSC 231", name: "Computer Organization", description: "Understanding hardware, memory, and low-level systems — critical for exploit analysis.", bestProfessor: "Dr. Tabor", difficulty: 4 },
      { code: "CSC 222", name: "Data Structures", description: "Algorithmic thinking for analyzing and building secure systems.", bestProfessor: "Dr. Ramanujan", difficulty: 3 },
      { code: "MAT 150", name: "Discrete Mathematics", description: "Logic, number theory, and cryptographic foundations.", bestProfessor: "Dr. Hossain", difficulty: 3 },
      { code: "PHI 220", name: "Ethics", description: "Ethical frameworks for responsible security research and disclosure.", bestProfessor: "Dr. McKeever", difficulty: 3 },
    ],
    summerOpportunities: [
      { title: "Security Internship", type: "Internship", description: "Work on security teams at companies like CrowdStrike, Palo Alto Networks, or major banks.", timing: "Summer after Sophomore or Junior year" },
      { title: "CTF Competitions", type: "Competition", description: "Compete in Capture the Flag cybersecurity competitions to sharpen skills.", timing: "Year-round" },
      { title: "Security Certifications", type: "Preparation", description: "Study for CompTIA Security+ or other entry-level certifications.", timing: "Any summer" },
    ],
    networking: [
      { role: "CS Faculty", type: "Faculty", description: "Mentorship in systems and security topics.", howToConnect: "Take systems courses and express interest in security research" },
      { role: "Security Professionals", type: "Professional", description: "Connect with industry professionals for mentorship.", howToConnect: "Attend DEF CON, BSides, or local security meetups" },
    ],
  },
  {
    id: "financial-planning",
    title: "Financial Planning & Wealth Management",
    icon: "Wallet",
    description: "Help individuals and families build, protect, and grow their wealth through personalized financial strategies.",
    tags: ["Analytical", "Work-Life Balance"],
    salaryRange: { min: 60000, max: 150000 },
    skills: ["Financial Analysis", "Client Relations", "Tax Planning", "Investment Strategy", "Communication"],
    whatYoullDo: [
      "Create comprehensive financial plans for clients",
      "Analyze investment portfolios and recommend adjustments",
      "Advise on retirement planning, tax strategy, and estate planning",
      "Build long-term client relationships based on trust",
      "Stay current on financial regulations and market trends",
    ],
    dayInLife: "Your morning starts with reviewing market updates and portfolio performance for today's client meetings. You meet with a young couple to discuss their retirement savings strategy and college planning. After lunch, you analyze a client's tax situation to optimize their year-end strategy. The afternoon involves preparing a financial plan presentation and making follow-up calls. You end the day attending a networking dinner with prospective clients.",
    courses: [
      { code: "ECO 101", name: "Principles of Economics", description: "Foundational understanding of markets, interest rates, and fiscal policy.", bestProfessor: "Dr. Griffith", difficulty: 2 },
      { code: "ECO 315", name: "Financial Economics", description: "Asset pricing, portfolio theory, and capital market dynamics.", bestProfessor: "Dr. Stroup", difficulty: 4 },
      { code: "MAT 220", name: "Probability & Statistics I", description: "Risk assessment and quantitative analysis for financial planning.", bestProfessor: "Dr. Blake", difficulty: 3 },
      { code: "ACC 215", name: "Financial Accounting", description: "Reading and interpreting financial statements.", bestProfessor: "Dr. Palmer", difficulty: 3 },
      { code: "PSY 100", name: "Introduction to Psychology", description: "Understanding client behavior, risk tolerance, and decision-making.", bestProfessor: "Dr. Bagwell", difficulty: 2 },
    ],
    summerOpportunities: [
      { title: "Wealth Management Internship", type: "Internship", description: "Intern at firms like Edward Jones, Merrill Lynch, or RBC Wealth Management.", timing: "Summer after Sophomore or Junior year" },
      { title: "CFP Study Program", type: "Preparation", description: "Begin coursework toward the Certified Financial Planner certification.", timing: "Senior year or post-graduation" },
      { title: "Investment Club", type: "Club", description: "Manage a simulated portfolio and learn investment analysis.", timing: "Year-round" },
    ],
    networking: [
      { role: "Economics Faculty", type: "Faculty", description: "Guidance on finance-track coursework and career options.", howToConnect: "Take financial economics courses and attend department events" },
      { role: "Finance Alumni", type: "Alumni", description: "Davidson alumni in wealth management and advisory roles.", howToConnect: "Alumni career panels and LinkedIn outreach" },
    ],
  },
  {
    id: "psychology-counseling",
    title: "Psychology & Counseling",
    icon: "Brain",
    description: "Help people understand themselves, overcome challenges, and improve their mental health through therapy and research.",
    tags: ["Work-Life Balance", "Analytical"],
    salaryRange: { min: 50000, max: 120000 },
    skills: ["Active Listening", "Clinical Assessment", "Research Methods", "Empathy", "Case Documentation"],
    whatYoullDo: [
      "Conduct therapy sessions with individuals, couples, or groups",
      "Administer and interpret psychological assessments",
      "Develop treatment plans based on evidence-based approaches",
      "Maintain detailed clinical documentation",
      "Collaborate with other healthcare professionals on patient care",
    ],
    dayInLife: "Your morning begins with reviewing notes from yesterday's sessions and preparing for today's clients. You see three individual therapy clients in the morning, using CBT and mindfulness techniques. After lunch, you lead a group therapy session for anxiety management. The afternoon includes a case consultation with colleagues, writing session notes, and reviewing research literature on a new treatment modality.",
    courses: [
      { code: "PSY 100", name: "Introduction to Psychology", description: "Survey of major psychological theories and research methods.", bestProfessor: "Dr. Bagwell", difficulty: 2 },
      { code: "PSY 230", name: "Developmental Psychology", description: "Cognitive, social, and emotional development across the lifespan.", bestProfessor: "Dr. Bagwell", difficulty: 3 },
      { code: "PSY 250", name: "Abnormal Psychology", description: "Understanding psychological disorders, diagnosis, and treatment.", bestProfessor: "Dr. Bagwell", difficulty: 3 },
      { code: "MAT 220", name: "Probability & Statistics I", description: "Statistical methods for psychology research.", bestProfessor: "Dr. Blake", difficulty: 3 },
      { code: "BIO 111", name: "Introductory Biology I", description: "Biological foundations of behavior and neuroscience.", bestProfessor: "Dr. Johnson", difficulty: 3 },
    ],
    summerOpportunities: [
      { title: "Research Assistantship", type: "Research", description: "Work in a psychology lab at Davidson or an external university.", timing: "Summer after Sophomore year" },
      { title: "Crisis Hotline Volunteer", type: "Service", description: "Gain counseling experience through crisis intervention work.", timing: "Year-round" },
      { title: "GRE/Clinical Prep", type: "Preparation", description: "Prepare for graduate school applications in clinical or counseling psychology.", timing: "Summer after Junior year" },
    ],
    networking: [
      { role: "Psychology Faculty", type: "Faculty", description: "Research mentorship and graduate school recommendation letters.", howToConnect: "Engage in lab research and attend department colloquia" },
      { role: "Psychology Alumni", type: "Alumni", description: "Davidson graduates in clinical practice and research.", howToConnect: "Alumni panels and faculty introductions" },
    ],
  },
  {
    id: "international-development",
    title: "International Development",
    icon: "Globe",
    description: "Work across borders to reduce poverty, improve governance, and promote sustainable development in communities worldwide.",
    tags: ["Leadership", "Work-Life Balance"],
    salaryRange: { min: 45000, max: 105000 },
    skills: ["Cross-Cultural Communication", "Policy Analysis", "Project Management", "Languages", "Data Analysis"],
    whatYoullDo: [
      "Design and manage development programs in partner countries",
      "Conduct field research and needs assessments",
      "Write grants and manage donor relationships",
      "Evaluate program impact using quantitative and qualitative methods",
      "Coordinate with local governments and community organizations",
    ],
    dayInLife: "Your morning starts with a video call to a field office in Nairobi reviewing project milestones. You spend mid-morning editing a grant proposal for USAID. After lunch, you analyze survey data from a maternal health program to measure impact. The afternoon involves a coordination meeting with partner NGOs and drafting a briefing document for your organization's leadership on policy changes in the region.",
    courses: [
      { code: "POL 250", name: "International Relations", description: "Global political systems and international cooperation frameworks.", bestProfessor: "Dr. Roberts", difficulty: 3 },
      { code: "ECO 101", name: "Principles of Economics", description: "Development economics and global economic systems.", bestProfessor: "Dr. Griffith", difficulty: 2 },
      { code: "ANT 200", name: "Ethnographic Methods", description: "Qualitative research methods for understanding communities.", bestProfessor: "Dr. Bowles", difficulty: 3 },
      { code: "SOC 101", name: "Introduction to Sociology", description: "Social structures, inequality, and institutional analysis.", bestProfessor: "Dr. Rivera", difficulty: 2 },
      { code: "PBH 200", name: "Global Public Health", description: "Health systems and disease prevention in developing contexts.", bestProfessor: "Dr. Chillag", difficulty: 3 },
    ],
    summerOpportunities: [
      { title: "NGO Internship Abroad", type: "Internship", description: "Work with organizations like the UN, World Bank, Peace Corps, or smaller NGOs.", timing: "Summer after Sophomore or Junior year" },
      { title: "Study Abroad", type: "Experience", description: "Immersive language and culture programs in the developing world.", timing: "Junior year" },
      { title: "Grant Writing Workshop", type: "Workshop", description: "Learn grant writing and fundraising for development projects.", timing: "Senior year" },
    ],
    networking: [
      { role: "Political Science & Anthro Faculty", type: "Faculty", description: "Mentorship on international careers and fieldwork opportunities.", howToConnect: "Take courses on global issues and pursue independent study" },
      { role: "Alumni in Development", type: "Alumni", description: "Davidson graduates at NGOs, the UN, and international organizations.", howToConnect: "Alumni panels and faculty referrals" },
    ],
  },
  {
    id: "architecture-urban-planning",
    title: "Architecture & Urban Planning",
    icon: "Building2",
    description: "Shape the built environment — design buildings, plan communities, and create spaces where people live, work, and thrive.",
    tags: ["Creative", "Analytical"],
    salaryRange: { min: 55000, max: 130000 },
    skills: ["Design Thinking", "CAD Software", "Spatial Analysis", "Sustainability", "Project Management"],
    whatYoullDo: [
      "Design buildings, public spaces, and urban environments",
      "Create architectural drawings, models, and 3D renderings",
      "Conduct site analysis and feasibility studies",
      "Manage construction projects and coordinate with engineers",
      "Develop zoning plans and urban development strategies",
    ],
    dayInLife: "Your morning starts with a design review meeting where the team critiques a mixed-use development concept. You spend mid-morning refining floor plans in Revit and adjusting the building's environmental performance model. After lunch, you visit a construction site to check progress against your drawings. The afternoon involves a meeting with city planners about zoning requirements and sketching alternative façade designs.",
    courses: [
      { code: "ART 120", name: "Visual Design", description: "Foundational design principles — composition, form, and spatial awareness.", bestProfessor: "Prof. St. Clair", difficulty: 2 },
      { code: "ENV 101", name: "Environmental Science", description: "Sustainable design and environmental impact of the built environment.", bestProfessor: "Dr. Chillag", difficulty: 2 },
      { code: "PHY 120", name: "General Physics I", description: "Mechanics and structural engineering fundamentals.", bestProfessor: "Dr. Barker", difficulty: 3 },
      { code: "MAT 110", name: "Calculus I", description: "Mathematical foundations for engineering and spatial calculations.", bestProfessor: "Dr. Blake", difficulty: 3 },
      { code: "HIS 200", name: "American History", description: "History of urban development and architectural movements.", bestProfessor: "Dr. Aldridge", difficulty: 2 },
    ],
    summerOpportunities: [
      { title: "Architecture Firm Internship", type: "Internship", description: "Work at architecture or urban planning firms to build portfolio.", timing: "Summer after Sophomore or Junior year" },
      { title: "Design-Build Project", type: "Project", description: "Participate in community design-build projects with Habitat or similar orgs.", timing: "Any summer" },
      { title: "Graduate School Portfolio Prep", type: "Preparation", description: "Build a portfolio of design work for M.Arch applications.", timing: "Senior year" },
    ],
    networking: [
      { role: "Art & Environmental Studies Faculty", type: "Faculty", description: "Mentorship in design thinking and sustainability.", howToConnect: "Take studio art and environmental design courses" },
      { role: "Architecture Alumni", type: "Alumni", description: "Davidson graduates in architecture and urban planning.", howToConnect: "Alumni network and AIA events" },
    ],
  },
  {
    id: "sports-management",
    title: "Sports Management",
    icon: "Trophy",
    description: "Combine a passion for athletics with business acumen — manage teams, events, brands, and the business side of sports.",
    tags: ["Leadership", "Creative"],
    salaryRange: { min: 45000, max: 120000 },
    skills: ["Event Management", "Marketing", "Negotiation", "Analytics", "Public Relations"],
    whatYoullDo: [
      "Manage operations for sports teams and athletic organizations",
      "Negotiate contracts and sponsorship deals",
      "Plan and execute sporting events and fan experiences",
      "Analyze player and team performance data",
      "Build brand partnerships and marketing campaigns",
    ],
    dayInLife: "Your morning starts with a team operations meeting to plan the upcoming home game weekend. You review ticket sales data and adjust pricing strategy. Mid-morning, you join a call with a potential corporate sponsor. After lunch, you coordinate with the events team on logistics for a community outreach program. The afternoon involves reviewing a player contract draft with legal and preparing social media content for the team's channels.",
    courses: [
      { code: "ECO 101", name: "Principles of Economics", description: "Business and market fundamentals for sports industry.", bestProfessor: "Dr. Griffith", difficulty: 2 },
      { code: "COM 210", name: "Public Speaking", description: "Media relations and public communication skills.", bestProfessor: "Dr. Martinez", difficulty: 2 },
      { code: "PSY 100", name: "Introduction to Psychology", description: "Team dynamics, motivation, and sports psychology foundations.", bestProfessor: "Dr. Bagwell", difficulty: 2 },
      { code: "MAT 220", name: "Probability & Statistics I", description: "Sports analytics and performance data interpretation.", bestProfessor: "Dr. Blake", difficulty: 3 },
      { code: "SOC 101", name: "Introduction to Sociology", description: "Sports as a social institution — culture, race, and identity in athletics.", bestProfessor: "Dr. Rivera", difficulty: 2 },
    ],
    summerOpportunities: [
      { title: "Sports Team Internship", type: "Internship", description: "Work with MLB, NBA, NFL, or MLS teams in operations, marketing, or analytics.", timing: "Summer after Sophomore or Junior year" },
      { title: "Athletic Department Assistant", type: "Experience", description: "Gain hands-on experience working with Davidson Athletics.", timing: "Year-round" },
      { title: "Sports Analytics Project", type: "Project", description: "Build a sports analytics portfolio using public data sets.", timing: "Any time" },
    ],
    networking: [
      { role: "Davidson Athletics Staff", type: "Advisor", description: "Build relationships with athletics department administrators.", howToConnect: "Volunteer for game-day operations and department events" },
      { role: "Sports Industry Alumni", type: "Alumni", description: "Davidson graduates working in professional and collegiate sports.", howToConnect: "Alumni network and sports industry conferences" },
    ],
  },
  {
    id: "healthcare-administration",
    title: "Healthcare Administration",
    icon: "Hospital",
    description: "Lead hospitals, health systems, and healthcare organizations — managing operations, policy, and the business of care delivery.",
    tags: ["Leadership", "High Salary"],
    salaryRange: { min: 65000, max: 160000 },
    skills: ["Operations Management", "Healthcare Policy", "Financial Management", "Leadership", "Data Analysis"],
    whatYoullDo: [
      "Oversee daily operations of healthcare facilities and departments",
      "Manage budgets, staffing, and resource allocation",
      "Ensure regulatory compliance and quality standards",
      "Develop strategic plans for organizational growth",
      "Improve patient experience and operational efficiency",
    ],
    dayInLife: "Your morning starts with a leadership huddle reviewing overnight census, patient flow, and any operational issues. You review quarterly budget reports and identify cost-saving opportunities. After lunch, you meet with department heads to discuss quality improvement initiatives. The afternoon involves a compliance review session and planning for a new community health program. You end the day preparing a board presentation on the hospital's strategic plan.",
    courses: [
      { code: "BIO 111", name: "Introductory Biology I", description: "Understanding the science foundation of healthcare.", bestProfessor: "Dr. Johnson", difficulty: 3 },
      { code: "ECO 101", name: "Principles of Economics", description: "Healthcare economics and resource allocation.", bestProfessor: "Dr. Griffith", difficulty: 2 },
      { code: "PBH 200", name: "Global Public Health", description: "Population health, epidemiology, and health systems.", bestProfessor: "Dr. Chillag", difficulty: 3 },
      { code: "MAT 220", name: "Probability & Statistics I", description: "Data analysis for quality improvement and outcomes research.", bestProfessor: "Dr. Blake", difficulty: 3 },
      { code: "POL 101", name: "American Government", description: "Healthcare policy, regulation, and the ACA.", bestProfessor: "Dr. Roberts", difficulty: 2 },
    ],
    summerOpportunities: [
      { title: "Hospital Administration Internship", type: "Internship", description: "Work in hospital operations, finance, or strategy departments.", timing: "Summer after Junior year" },
      { title: "Health Policy Research", type: "Research", description: "Research healthcare policy with public health or political science faculty.", timing: "Summer after Sophomore year" },
      { title: "MHA/MBA Preparation", type: "Preparation", description: "Prepare applications for Master of Health Administration or MBA programs.", timing: "Senior year" },
    ],
    networking: [
      { role: "Public Health Faculty", type: "Faculty", description: "Mentorship on healthcare careers and graduate school prep.", howToConnect: "Take public health courses and seek research opportunities" },
      { role: "Healthcare Alumni", type: "Alumni", description: "Davidson alumni in hospital leadership and health system roles.", howToConnect: "Alumni panels and healthcare career fairs" },
    ],
  },
  {
    id: "arts-museum-curation",
    title: "Arts & Museum Curation",
    icon: "Frame",
    description: "Preserve, interpret, and share cultural heritage — curate exhibitions, manage collections, and connect communities with art and history.",
    tags: ["Creative", "Work-Life Balance"],
    salaryRange: { min: 40000, max: 95000 },
    skills: ["Art History", "Research", "Exhibition Design", "Writing", "Collections Management"],
    whatYoullDo: [
      "Research and curate exhibitions that tell compelling stories",
      "Manage and preserve museum collections and archives",
      "Write exhibition labels, catalogs, and educational materials",
      "Collaborate with artists, donors, and community groups",
      "Plan public programs and educational outreach",
    ],
    dayInLife: "Your morning starts reviewing condition reports for artworks arriving on loan. You spend mid-morning in the archives researching a 19th-century textile collection for an upcoming exhibition. After lunch, you walk the galleries with the exhibition designer, discussing layout and lighting. The afternoon involves writing interpretive text for a new installation and meeting with a local school group about an educational partnership. You end the day reviewing a grant application.",
    courses: [
      { code: "ART 120", name: "Visual Design", description: "Foundational understanding of artistic principles and visual literacy.", bestProfessor: "Prof. St. Clair", difficulty: 2 },
      { code: "HIS 200", name: "American History", description: "Historical context for cultural artifacts and museum collections.", bestProfessor: "Dr. Aldridge", difficulty: 2 },
      { code: "ENG 270", name: "Expository Writing", description: "Clear, accessible writing for exhibition labels and catalogs.", bestProfessor: "Dr. Rippeon", difficulty: 3 },
      { code: "ANT 200", name: "Ethnographic Methods", description: "Material culture analysis and community-engaged research.", bestProfessor: "Dr. Bowles", difficulty: 3 },
      { code: "CLA 200", name: "Classical Archaeology", description: "Understanding archaeological methods and artifact analysis.", bestProfessor: "Prof. Smith", difficulty: 3 },
    ],
    summerOpportunities: [
      { title: "Museum Internship", type: "Internship", description: "Work at museums like the Smithsonian, MoMA, or local galleries.", timing: "Summer after Sophomore or Junior year" },
      { title: "Gallery Assistantship", type: "Experience", description: "Work in Davidson's Van Every/Smith Galleries managing exhibitions.", timing: "Year-round" },
      { title: "Art History Research", type: "Research", description: "Research with art faculty on visual culture or museum studies.", timing: "Any summer" },
    ],
    networking: [
      { role: "Art Faculty & Gallery Staff", type: "Faculty", description: "Mentorship in curatorial practice and art history research.", howToConnect: "Take art history courses and volunteer at campus galleries" },
      { role: "Museum Alumni", type: "Alumni", description: "Davidson graduates working in museums and cultural institutions.", howToConnect: "Alumni network and museum professional organizations" },
    ],
  },
];
