// Comprehensive Davidson College course data
// Based on real departments and course offerings

export interface SeedCourse {
  code: string;
  name: string;
  description: string;
  credits: number;
  department: string;
  prerequisites: string[];
  offered: ("Fall" | "Spring" | "Summer")[];
  tags: string[];
  difficulty: number;
  professor?: string;
  professorRating?: number;
  careerRelevance: { field: string; relevance: number }[];
}

export const DAVIDSON_COURSES: SeedCourse[] = [
  // ===== COMPUTER SCIENCE =====
  { code: "CSC 121", name: "Programming and Problem Solving", description: "Introduction to computer science through programming. Topics include variables, control structures, functions, arrays, and object-oriented design.", credits: 4, department: "Computer Science", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "major-requirement"], difficulty: 2, professor: "Dr. Tabitha Peck", professorRating: 4.5, careerRelevance: [{ field: "Software Engineering", relevance: 0.9 }, { field: "Data Science & Analytics", relevance: 0.7 }] },
  { code: "CSC 222", name: "Data Structures", description: "Study of fundamental data structures including lists, stacks, queues, trees, and graphs. Algorithm analysis and design.", credits: 4, department: "Computer Science", prerequisites: ["CSC 121"], offered: ["Fall", "Spring"], tags: ["core", "major-requirement"], difficulty: 3, professor: "Dr. Raghu Ramanujan", professorRating: 4.7, careerRelevance: [{ field: "Software Engineering", relevance: 0.95 }, { field: "Data Science & Analytics", relevance: 0.8 }] },
  { code: "CSC 231", name: "Computer Organization and Assembly", description: "Computer architecture, assembly language, digital logic, and machine-level programming.", credits: 4, department: "Computer Science", prerequisites: ["CSC 121"], offered: ["Spring"], tags: ["major-requirement"], difficulty: 4, professor: "Dr. Richard Shillcock", professorRating: 4.2, careerRelevance: [{ field: "Software Engineering", relevance: 0.7 }] },
  { code: "CSC 250", name: "Discrete Mathematics", description: "Mathematical foundations of computer science including logic, sets, functions, relations, and graph theory.", credits: 4, department: "Computer Science", prerequisites: ["CSC 121", "MAT 112"], offered: ["Fall"], tags: ["major-requirement"], difficulty: 3, professor: "Dr. Tabitha Peck", professorRating: 4.5, careerRelevance: [{ field: "Software Engineering", relevance: 0.6 }, { field: "Data Science & Analytics", relevance: 0.5 }] },
  { code: "CSC 321", name: "Analysis of Algorithms", description: "Design and analysis of algorithms. Topics include sorting, graph algorithms, dynamic programming, and NP-completeness.", credits: 4, department: "Computer Science", prerequisites: ["CSC 222", "CSC 250"], offered: ["Fall"], tags: ["major-requirement"], difficulty: 4, professor: "Dr. Raghu Ramanujan", professorRating: 4.7, careerRelevance: [{ field: "Software Engineering", relevance: 0.9 }, { field: "Data Science & Analytics", relevance: 0.7 }] },
  { code: "CSC 341", name: "Operating Systems", description: "Operating system concepts including processes, memory management, file systems, and concurrency.", credits: 4, department: "Computer Science", prerequisites: ["CSC 222", "CSC 231"], offered: ["Spring"], tags: ["elective"], difficulty: 4, professor: "Dr. Richard Shillcock", professorRating: 4.2, careerRelevance: [{ field: "Software Engineering", relevance: 0.8 }] },
  { code: "CSC 371", name: "Database Systems", description: "Design and implementation of database systems. SQL, relational algebra, normalization, and transaction processing.", credits: 4, department: "Computer Science", prerequisites: ["CSC 222"], offered: ["Spring"], tags: ["elective"], difficulty: 3, professor: "Dr. Tabitha Peck", professorRating: 4.5, careerRelevance: [{ field: "Software Engineering", relevance: 0.85 }, { field: "Data Science & Analytics", relevance: 0.9 }] },
  { code: "CSC 361", name: "Artificial Intelligence", description: "Introduction to AI including search, knowledge representation, machine learning, and neural networks.", credits: 4, department: "Computer Science", prerequisites: ["CSC 222"], offered: ["Fall"], tags: ["elective"], difficulty: 4, professor: "Dr. Raghu Ramanujan", professorRating: 4.7, careerRelevance: [{ field: "Software Engineering", relevance: 0.8 }, { field: "Data Science & Analytics", relevance: 0.95 }] },
  { code: "CSC 381", name: "Software Engineering", description: "Software development methodologies, project management, testing, and team-based development.", credits: 4, department: "Computer Science", prerequisites: ["CSC 222"], offered: ["Spring"], tags: ["elective"], difficulty: 3, professor: "Dr. Tabitha Peck", professorRating: 4.5, careerRelevance: [{ field: "Software Engineering", relevance: 0.95 }, { field: "Product Management", relevance: 0.6 }] },

  // ===== ECONOMICS =====
  { code: "ECO 101", name: "Principles of Economics", description: "Introduction to micro and macroeconomic concepts including supply and demand, market structures, GDP, and monetary policy.", credits: 4, department: "Economics", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "major-requirement", "distribution"], difficulty: 2, professor: "Dr. David Martin", professorRating: 4.3, careerRelevance: [{ field: "Finance & Banking", relevance: 0.8 }, { field: "Consulting", relevance: 0.7 }, { field: "Government & Policy", relevance: 0.6 }] },
  { code: "ECO 201", name: "Intermediate Microeconomics", description: "Consumer theory, producer theory, market structures, game theory, and welfare economics.", credits: 4, department: "Economics", prerequisites: ["ECO 101", "MAT 112"], offered: ["Fall"], tags: ["major-requirement"], difficulty: 3, professor: "Dr. Peter Hartley", professorRating: 4.1, careerRelevance: [{ field: "Finance & Banking", relevance: 0.85 }, { field: "Consulting", relevance: 0.8 }] },
  { code: "ECO 202", name: "Intermediate Macroeconomics", description: "National income accounting, IS-LM model, fiscal and monetary policy, economic growth theories.", credits: 4, department: "Economics", prerequisites: ["ECO 101", "MAT 112"], offered: ["Spring"], tags: ["major-requirement"], difficulty: 3, professor: "Dr. David Martin", professorRating: 4.3, careerRelevance: [{ field: "Finance & Banking", relevance: 0.85 }, { field: "Government & Policy", relevance: 0.8 }] },
  { code: "ECO 250", name: "Statistics and Econometrics", description: "Statistical methods for economic analysis. Regression analysis, hypothesis testing, and empirical research methods.", credits: 4, department: "Economics", prerequisites: ["ECO 101", "MAT 112"], offered: ["Fall", "Spring"], tags: ["major-requirement"], difficulty: 3, professor: "Dr. Sarah Jacobson", professorRating: 4.6, careerRelevance: [{ field: "Finance & Banking", relevance: 0.9 }, { field: "Data Science & Analytics", relevance: 0.85 }, { field: "Consulting", relevance: 0.7 }] },
  { code: "ECO 310", name: "Money and Banking", description: "Financial markets and institutions, the Federal Reserve, monetary policy, and banking regulation.", credits: 4, department: "Economics", prerequisites: ["ECO 201", "ECO 202"], offered: ["Fall"], tags: ["elective"], difficulty: 3, professor: "Dr. Peter Hartley", professorRating: 4.1, careerRelevance: [{ field: "Finance & Banking", relevance: 0.95 }, { field: "Consulting", relevance: 0.6 }] },
  { code: "ECO 350", name: "International Trade and Finance", description: "Trade theory, exchange rates, balance of payments, international monetary systems.", credits: 4, department: "Economics", prerequisites: ["ECO 201", "ECO 202"], offered: ["Spring"], tags: ["elective"], difficulty: 3, professor: "Dr. David Martin", professorRating: 4.3, careerRelevance: [{ field: "Finance & Banking", relevance: 0.8 }, { field: "Consulting", relevance: 0.75 }, { field: "Government & Policy", relevance: 0.7 }] },
  { code: "ECO 360", name: "Public Economics", description: "Role of government in the economy, taxation, public goods, externalities, and social insurance.", credits: 4, department: "Economics", prerequisites: ["ECO 201"], offered: ["Spring"], tags: ["elective"], difficulty: 3, professor: "Dr. Sarah Jacobson", professorRating: 4.6, careerRelevance: [{ field: "Government & Policy", relevance: 0.9 }, { field: "Nonprofit & Social Impact", relevance: 0.7 }] },

  // ===== MATHEMATICS =====
  { code: "MAT 112", name: "Calculus I", description: "Limits, derivatives, and integrals of single-variable functions. Applications to optimization and rates of change.", credits: 4, department: "Mathematics", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "distribution"], difficulty: 3, professor: "Dr. Donna Molinek", professorRating: 4.4, careerRelevance: [{ field: "Finance & Banking", relevance: 0.6 }, { field: "Data Science & Analytics", relevance: 0.7 }] },
  { code: "MAT 113", name: "Calculus II", description: "Techniques of integration, sequences and series, Taylor series, and parametric equations.", credits: 4, department: "Mathematics", prerequisites: ["MAT 112"], offered: ["Fall", "Spring"], tags: ["core"], difficulty: 3, professor: "Dr. Donna Molinek", professorRating: 4.4, careerRelevance: [{ field: "Data Science & Analytics", relevance: 0.6 }] },
  { code: "MAT 214", name: "Linear Algebra", description: "Vector spaces, linear transformations, matrices, determinants, eigenvalues, and diagonalization.", credits: 4, department: "Mathematics", prerequisites: ["MAT 113"], offered: ["Fall", "Spring"], tags: ["major-requirement"], difficulty: 3, professor: "Dr. Laurie Heyer", professorRating: 4.6, careerRelevance: [{ field: "Data Science & Analytics", relevance: 0.9 }, { field: "Software Engineering", relevance: 0.5 }] },
  { code: "MAT 220", name: "Multivariable Calculus", description: "Functions of several variables, partial derivatives, multiple integrals, vector calculus.", credits: 4, department: "Mathematics", prerequisites: ["MAT 113"], offered: ["Fall", "Spring"], tags: ["major-requirement"], difficulty: 4, professor: "Dr. Donna Molinek", professorRating: 4.4, careerRelevance: [{ field: "Data Science & Analytics", relevance: 0.7 }] },
  { code: "MAT 230", name: "Probability and Statistics", description: "Probability theory, random variables, distributions, estimation, and hypothesis testing.", credits: 4, department: "Mathematics", prerequisites: ["MAT 113"], offered: ["Fall", "Spring"], tags: ["major-requirement"], difficulty: 3, professor: "Dr. Tim Chartier", professorRating: 4.8, careerRelevance: [{ field: "Data Science & Analytics", relevance: 0.95 }, { field: "Finance & Banking", relevance: 0.8 }, { field: "Consulting", relevance: 0.6 }] },

  // ===== BIOLOGY =====
  { code: "BIO 111", name: "Molecules, Genes, and Cells", description: "Introduction to molecular biology, genetics, cell structure and function, and biotechnology.", credits: 4, department: "Biology", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "major-requirement", "distribution"], difficulty: 3, professor: "Dr. Barbara Lom", professorRating: 4.5, careerRelevance: [{ field: "Healthcare & Medicine", relevance: 0.9 }, { field: "Research & Academia", relevance: 0.7 }] },
  { code: "BIO 112", name: "Organisms and Ecosystems", description: "Ecology, evolution, organismal biology, and biodiversity.", credits: 4, department: "Biology", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "major-requirement", "distribution"], difficulty: 3, professor: "Dr. Mark Barsoum", professorRating: 4.2, careerRelevance: [{ field: "Healthcare & Medicine", relevance: 0.7 }, { field: "Environmental Science", relevance: 0.9 }] },
  { code: "BIO 220", name: "Genetics", description: "Principles of heredity, molecular genetics, gene expression, and genomics.", credits: 4, department: "Biology", prerequisites: ["BIO 111"], offered: ["Fall"], tags: ["major-requirement"], difficulty: 3, professor: "Dr. Barbara Lom", professorRating: 4.5, careerRelevance: [{ field: "Healthcare & Medicine", relevance: 0.9 }, { field: "Research & Academia", relevance: 0.85 }] },
  { code: "BIO 306", name: "Neuroscience", description: "Structure and function of the nervous system. Neural circuits, sensory systems, and cognitive neuroscience.", credits: 4, department: "Biology", prerequisites: ["BIO 111"], offered: ["Spring"], tags: ["elective"], difficulty: 4, professor: "Dr. Barbara Lom", professorRating: 4.5, careerRelevance: [{ field: "Healthcare & Medicine", relevance: 0.85 }, { field: "Research & Academia", relevance: 0.9 }] },

  // ===== CHEMISTRY =====
  { code: "CHE 115", name: "Principles of Chemistry", description: "Atomic structure, bonding, stoichiometry, thermochemistry, and introduction to organic chemistry.", credits: 4, department: "Chemistry", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "major-requirement", "distribution"], difficulty: 3, professor: "Dr. Nicole Snyder", professorRating: 4.3, careerRelevance: [{ field: "Healthcare & Medicine", relevance: 0.7 }, { field: "Environmental Science", relevance: 0.6 }] },
  { code: "CHE 230", name: "Organic Chemistry I", description: "Structure, reactivity, and synthesis of organic compounds. Stereochemistry and reaction mechanisms.", credits: 4, department: "Chemistry", prerequisites: ["CHE 115"], offered: ["Fall"], tags: ["major-requirement"], difficulty: 4, professor: "Dr. Nicole Snyder", professorRating: 4.3, careerRelevance: [{ field: "Healthcare & Medicine", relevance: 0.85 }] },

  // ===== PHYSICS =====
  { code: "PHY 120", name: "General Physics I", description: "Mechanics, thermodynamics, and waves. Calculus-based approach.", credits: 4, department: "Physics", prerequisites: ["MAT 112"], offered: ["Fall"], tags: ["core", "major-requirement", "distribution"], difficulty: 3, professor: "Dr. Mario Belloni", professorRating: 4.6, careerRelevance: [{ field: "Software Engineering", relevance: 0.3 }, { field: "Research & Academia", relevance: 0.7 }] },
  { code: "PHY 220", name: "General Physics II", description: "Electricity, magnetism, optics, and modern physics.", credits: 4, department: "Physics", prerequisites: ["PHY 120", "MAT 113"], offered: ["Spring"], tags: ["major-requirement"], difficulty: 4, professor: "Dr. Mario Belloni", professorRating: 4.6, careerRelevance: [{ field: "Research & Academia", relevance: 0.8 }] },

  // ===== PSYCHOLOGY =====
  { code: "PSY 100", name: "General Psychology", description: "Survey of major areas in psychology including cognition, development, social behavior, and psychopathology.", credits: 4, department: "Psychology", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "major-requirement", "distribution"], difficulty: 2, professor: "Dr. Mark Smith", professorRating: 4.4, careerRelevance: [{ field: "Healthcare & Medicine", relevance: 0.7 }, { field: "Education", relevance: 0.6 }, { field: "Consulting", relevance: 0.4 }] },
  { code: "PSY 210", name: "Research Methods", description: "Experimental design, data analysis, and scientific writing in psychology.", credits: 4, department: "Psychology", prerequisites: ["PSY 100"], offered: ["Fall", "Spring"], tags: ["major-requirement"], difficulty: 3, professor: "Dr. Mark Smith", professorRating: 4.4, careerRelevance: [{ field: "Research & Academia", relevance: 0.8 }, { field: "Data Science & Analytics", relevance: 0.5 }] },
  { code: "PSY 310", name: "Cognitive Psychology", description: "Attention, perception, memory, language, and decision-making processes.", credits: 4, department: "Psychology", prerequisites: ["PSY 100"], offered: ["Fall"], tags: ["elective"], difficulty: 3, professor: "Dr. Mark Smith", professorRating: 4.4, careerRelevance: [{ field: "Product Management", relevance: 0.6 }, { field: "Healthcare & Medicine", relevance: 0.5 }] },

  // ===== POLITICAL SCIENCE =====
  { code: "POL 101", name: "American Government", description: "Institutions, processes, and politics of the American political system.", credits: 4, department: "Political Science", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "major-requirement", "distribution"], difficulty: 2, professor: "Dr. Susan Roberts", professorRating: 4.3, careerRelevance: [{ field: "Government & Policy", relevance: 0.9 }, { field: "Law", relevance: 0.7 }] },
  { code: "POL 210", name: "International Relations", description: "Theories and practices of international politics, conflict, cooperation, and global governance.", credits: 4, department: "Political Science", prerequisites: [], offered: ["Fall"], tags: ["major-requirement"], difficulty: 3, professor: "Dr. Susan Roberts", professorRating: 4.3, careerRelevance: [{ field: "Government & Policy", relevance: 0.85 }, { field: "Consulting", relevance: 0.5 }, { field: "Nonprofit & Social Impact", relevance: 0.7 }] },
  { code: "POL 310", name: "Constitutional Law", description: "Supreme Court decisions on federalism, separation of powers, and individual rights.", credits: 4, department: "Political Science", prerequisites: ["POL 101"], offered: ["Spring"], tags: ["elective"], difficulty: 3, professor: "Dr. Susan Roberts", professorRating: 4.3, careerRelevance: [{ field: "Law", relevance: 0.95 }, { field: "Government & Policy", relevance: 0.8 }] },

  // ===== ENGLISH =====
  { code: "ENG 101", name: "Literature and Interpretation", description: "Introduction to literary analysis through close reading of poetry, fiction, drama, and essays.", credits: 4, department: "English", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "major-requirement", "distribution"], difficulty: 2, professor: "Dr. Shireen Campbell", professorRating: 4.5, careerRelevance: [{ field: "Marketing & Communications", relevance: 0.7 }, { field: "Media & Journalism", relevance: 0.8 }, { field: "Law", relevance: 0.5 }] },
  { code: "ENG 220", name: "Creative Writing", description: "Workshop-based course in fiction, poetry, and creative nonfiction writing.", credits: 4, department: "English", prerequisites: ["ENG 101"], offered: ["Fall", "Spring"], tags: ["elective"], difficulty: 2, professor: "Dr. Shireen Campbell", professorRating: 4.5, careerRelevance: [{ field: "Media & Journalism", relevance: 0.85 }, { field: "Marketing & Communications", relevance: 0.7 }] },

  // ===== HISTORY =====
  { code: "HIS 101", name: "World History to 1500", description: "Global perspectives on human civilizations from prehistory to the early modern period.", credits: 4, department: "History", prerequisites: [], offered: ["Fall"], tags: ["core", "distribution"], difficulty: 2, professor: "Dr. Mary Hepler", professorRating: 4.2, careerRelevance: [{ field: "Law", relevance: 0.4 }, { field: "Education", relevance: 0.6 }] },
  { code: "HIS 201", name: "United States History", description: "American history from colonial period to present with emphasis on social and political movements.", credits: 4, department: "History", prerequisites: [], offered: ["Fall", "Spring"], tags: ["major-requirement", "distribution"], difficulty: 2, professor: "Dr. Mary Hepler", professorRating: 4.2, careerRelevance: [{ field: "Law", relevance: 0.5 }, { field: "Government & Policy", relevance: 0.6 }, { field: "Education", relevance: 0.5 }] },

  // ===== SOCIOLOGY =====
  { code: "SOC 101", name: "Introduction to Sociology", description: "Social institutions, stratification, culture, and social change through sociological perspectives.", credits: 4, department: "Sociology", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "major-requirement", "distribution"], difficulty: 2, professor: "Dr. Gerardo Marti", professorRating: 4.5, careerRelevance: [{ field: "Nonprofit & Social Impact", relevance: 0.8 }, { field: "Government & Policy", relevance: 0.6 }, { field: "Education", relevance: 0.5 }] },
  { code: "SOC 230", name: "Social Inequality", description: "Analysis of race, class, gender, and other dimensions of inequality in contemporary society.", credits: 4, department: "Sociology", prerequisites: ["SOC 101"], offered: ["Spring"], tags: ["elective"], difficulty: 3, professor: "Dr. Gerardo Marti", professorRating: 4.5, careerRelevance: [{ field: "Nonprofit & Social Impact", relevance: 0.9 }, { field: "Government & Policy", relevance: 0.7 }, { field: "Law", relevance: 0.5 }] },

  // ===== COMMUNICATION STUDIES =====
  { code: "COM 100", name: "Introduction to Communication Studies", description: "Foundations of human communication including rhetoric, media studies, and interpersonal communication.", credits: 4, department: "Communication Studies", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "distribution"], difficulty: 2, professor: "Dr. Jean DeHart", professorRating: 4.3, careerRelevance: [{ field: "Marketing & Communications", relevance: 0.9 }, { field: "Media & Journalism", relevance: 0.8 }, { field: "Consulting", relevance: 0.5 }] },
  { code: "COM 250", name: "Public Speaking and Advocacy", description: "Theory and practice of persuasive speaking, argumentation, and civic engagement.", credits: 4, department: "Communication Studies", prerequisites: [], offered: ["Fall", "Spring"], tags: ["elective"], difficulty: 2, professor: "Dr. Jean DeHart", professorRating: 4.3, careerRelevance: [{ field: "Law", relevance: 0.7 }, { field: "Marketing & Communications", relevance: 0.8 }, { field: "Consulting", relevance: 0.7 }] },

  // ===== PHILOSOPHY =====
  { code: "PHI 101", name: "Introduction to Philosophy", description: "Fundamental questions of philosophy including knowledge, reality, ethics, and meaning.", credits: 4, department: "Philosophy", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "distribution"], difficulty: 2, professor: "Dr. Lance Factor", professorRating: 4.4, careerRelevance: [{ field: "Law", relevance: 0.7 }, { field: "Consulting", relevance: 0.4 }] },
  { code: "PHI 203", name: "Ethics", description: "Major ethical theories and their application to contemporary moral problems.", credits: 4, department: "Philosophy", prerequisites: [], offered: ["Fall", "Spring"], tags: ["elective"], difficulty: 2, professor: "Dr. Lance Factor", professorRating: 4.4, careerRelevance: [{ field: "Law", relevance: 0.8 }, { field: "Healthcare & Medicine", relevance: 0.5 }, { field: "Nonprofit & Social Impact", relevance: 0.6 }] },

  // ===== ENVIRONMENTAL STUDIES =====
  { code: "ENV 101", name: "Introduction to Environmental Studies", description: "Interdisciplinary approach to environmental issues including ecology, policy, and sustainability.", credits: 4, department: "Environmental Studies", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "major-requirement", "distribution"], difficulty: 2, professor: "Dr. Mark Barsoum", professorRating: 4.2, careerRelevance: [{ field: "Environmental Science", relevance: 0.95 }, { field: "Government & Policy", relevance: 0.6 }, { field: "Nonprofit & Social Impact", relevance: 0.7 }] },
  { code: "ENV 250", name: "Environmental Policy", description: "Analysis of environmental regulations, policy-making, and sustainability frameworks.", credits: 4, department: "Environmental Studies", prerequisites: ["ENV 101"], offered: ["Spring"], tags: ["major-requirement"], difficulty: 3, professor: "Dr. Mark Barsoum", professorRating: 4.2, careerRelevance: [{ field: "Environmental Science", relevance: 0.9 }, { field: "Government & Policy", relevance: 0.8 }, { field: "Nonprofit & Social Impact", relevance: 0.7 }] },

  // ===== PUBLIC HEALTH =====
  { code: "PUH 101", name: "Introduction to Public Health", description: "Overview of public health principles, epidemiology, health policy, and global health challenges.", credits: 4, department: "Public Health", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "major-requirement"], difficulty: 2, professor: "Dr. Arlene Davis", professorRating: 4.4, careerRelevance: [{ field: "Healthcare & Medicine", relevance: 0.9 }, { field: "Nonprofit & Social Impact", relevance: 0.7 }, { field: "Government & Policy", relevance: 0.6 }] },
  { code: "PUH 250", name: "Epidemiology", description: "Study of disease patterns, health determinants, and public health interventions.", credits: 4, department: "Public Health", prerequisites: ["PUH 101"], offered: ["Fall"], tags: ["major-requirement"], difficulty: 3, professor: "Dr. Arlene Davis", professorRating: 4.4, careerRelevance: [{ field: "Healthcare & Medicine", relevance: 0.95 }, { field: "Data Science & Analytics", relevance: 0.5 }] },

  // ===== ANTHROPOLOGY =====
  { code: "ANT 101", name: "Introduction to Anthropology", description: "Survey of cultural, biological, archaeological, and linguistic anthropology.", credits: 4, department: "Anthropology", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "distribution"], difficulty: 2, professor: "Dr. Flora Lu", professorRating: 4.5, careerRelevance: [{ field: "Nonprofit & Social Impact", relevance: 0.7 }, { field: "Research & Academia", relevance: 0.6 }] },

  // ===== ART =====
  { code: "ART 101", name: "Introduction to Studio Art", description: "Foundation course in visual arts exploring drawing, painting, sculpture, and digital media.", credits: 4, department: "Art", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "distribution"], difficulty: 2, professor: "Dr. Herb Jackson", professorRating: 4.7, careerRelevance: [{ field: "Arts & Design", relevance: 0.9 }, { field: "Media & Journalism", relevance: 0.4 }] },

  // ===== THEATRE =====
  { code: "THE 100", name: "Introduction to Theatre", description: "Survey of theatrical traditions, play analysis, and performance practices.", credits: 4, department: "Theatre", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "distribution"], difficulty: 2, professor: "Dr. Ann Marie Costa", professorRating: 4.6, careerRelevance: [{ field: "Arts & Design", relevance: 0.7 }, { field: "Marketing & Communications", relevance: 0.4 }] },

  // ===== MUSIC =====
  { code: "MUS 101", name: "Music in Western Culture", description: "Survey of Western music from the Middle Ages to the present, with emphasis on listening and analysis.", credits: 4, department: "Music", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "distribution"], difficulty: 2, professor: "Dr. Matthew Hoch", professorRating: 4.5, careerRelevance: [{ field: "Arts & Design", relevance: 0.7 }, { field: "Education", relevance: 0.4 }] },

  // ===== EDUCATIONAL STUDIES =====
  { code: "EDU 200", name: "Education in American Society", description: "Historical, philosophical, and sociological foundations of American education.", credits: 4, department: "Educational Studies", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "major-requirement"], difficulty: 2, professor: "Dr. Scott Novakowski", professorRating: 4.3, careerRelevance: [{ field: "Education", relevance: 0.95 }, { field: "Nonprofit & Social Impact", relevance: 0.6 }] },

  // ===== RELIGIOUS STUDIES =====
  { code: "REL 101", name: "Introduction to Religious Studies", description: "Comparative study of world religions including their beliefs, practices, and cultural contexts.", credits: 4, department: "Religious Studies", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "distribution"], difficulty: 2, professor: "Dr. Trent Foley", professorRating: 4.2, careerRelevance: [{ field: "Nonprofit & Social Impact", relevance: 0.5 }, { field: "Education", relevance: 0.4 }] },

  // ===== GENDER & SEXUALITY STUDIES =====
  { code: "GSS 101", name: "Introduction to Gender and Sexuality Studies", description: "Interdisciplinary exploration of gender identity, sexuality, feminism, and social justice.", credits: 4, department: "Gender & Sexuality Studies", prerequisites: [], offered: ["Fall"], tags: ["core", "distribution"], difficulty: 2, professor: "Dr. Susana Loza", professorRating: 4.4, careerRelevance: [{ field: "Nonprofit & Social Impact", relevance: 0.7 }, { field: "Law", relevance: 0.4 }, { field: "Government & Policy", relevance: 0.5 }] },

  // ===== AFRICANA STUDIES =====
  { code: "AFR 101", name: "Introduction to Africana Studies", description: "Interdisciplinary study of the experiences, cultures, and histories of people of African descent.", credits: 4, department: "Africana Studies", prerequisites: [], offered: ["Fall"], tags: ["core", "distribution"], difficulty: 2, professor: "Dr. Tiffany Barber", professorRating: 4.3, careerRelevance: [{ field: "Nonprofit & Social Impact", relevance: 0.7 }, { field: "Education", relevance: 0.5 }] },

  // ===== DATA SCIENCE (cross-listed) =====
  { code: "DAS 201", name: "Introduction to Data Science", description: "Data wrangling, visualization, statistical modeling, and machine learning with Python and R.", credits: 4, department: "Digital Studies", prerequisites: ["MAT 112"], offered: ["Fall", "Spring"], tags: ["elective"], difficulty: 3, professor: "Dr. Tim Chartier", professorRating: 4.8, careerRelevance: [{ field: "Data Science & Analytics", relevance: 0.95 }, { field: "Finance & Banking", relevance: 0.7 }, { field: "Consulting", relevance: 0.6 }] },
  { code: "DAS 301", name: "Machine Learning", description: "Supervised and unsupervised learning, deep learning, model evaluation and deployment.", credits: 4, department: "Digital Studies", prerequisites: ["DAS 201", "MAT 214"], offered: ["Spring"], tags: ["elective"], difficulty: 4, professor: "Dr. Tim Chartier", professorRating: 4.8, careerRelevance: [{ field: "Data Science & Analytics", relevance: 0.95 }, { field: "Software Engineering", relevance: 0.7 }] },

  // ===== FILM & MEDIA STUDIES =====
  { code: "FMS 101", name: "Introduction to Film Studies", description: "Analysis of film as art and cultural artifact. Film history, theory, and critical approaches.", credits: 4, department: "Film & Media Studies", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "distribution"], difficulty: 2, professor: "Dr. Cynthia Lewis", professorRating: 4.3, careerRelevance: [{ field: "Media & Journalism", relevance: 0.8 }, { field: "Arts & Design", relevance: 0.6 }] },

  // ===== LANGUAGES =====
  { code: "FRE 101", name: "Elementary French I", description: "Introduction to French language and Francophone cultures.", credits: 4, department: "French", prerequisites: [], offered: ["Fall"], tags: ["core", "distribution"], difficulty: 2, professor: "Dr. Sophie Adamson", professorRating: 4.3, careerRelevance: [{ field: "Consulting", relevance: 0.4 }, { field: "Government & Policy", relevance: 0.4 }] },
  { code: "SPA 101", name: "Elementary Spanish I", description: "Introduction to Spanish language and Hispanic cultures.", credits: 4, department: "Hispanic Studies", prerequisites: [], offered: ["Fall", "Spring"], tags: ["core", "distribution"], difficulty: 2, professor: "Dr. Maria Caballero", professorRating: 4.5, careerRelevance: [{ field: "Healthcare & Medicine", relevance: 0.4 }, { field: "Nonprofit & Social Impact", relevance: 0.4 }] },
  { code: "CHI 101", name: "Elementary Chinese I", description: "Introduction to Mandarin Chinese language and culture.", credits: 4, department: "Chinese", prerequisites: [], offered: ["Fall"], tags: ["core", "distribution"], difficulty: 3, professor: "Dr. Jie Guo", professorRating: 4.2, careerRelevance: [{ field: "Finance & Banking", relevance: 0.4 }, { field: "Consulting", relevance: 0.4 }] },
];
