/**
 * Where aggregated items come from (PLAN §4.1.13, §5 "Sources (truthfulness)"). Every aggregated item stores one
 * of these ids in its `source` field and renders it with `<SourceTag source>`: a small uppercase tag
 * (Broadsheet idea adopted for Lakeside: WILDCATSYNC, HANDSHAKE, DAVIDSON ONE, YOUR PLAN, ...).
 *
 * - `label` is the name in normal case. SourceTag and the Sources panel render it; the tag uppercases it with CSS
 *   so screen readers read words, not letters.
 * - `tag` is exactly what the tag shows (`label` in upper case). Use it in plain-text contexts (print view,
 *   "Copy for WebTree", tests); never build tag text any other way.
 * - `kind` says how MakeItSo gets the data, which decides where the Sources panel lists it:
 *     api      synced from an upstream API (last-sync time shown)
 *     feed     synced from an ICS/RSS/JSON feed (last-sync time shown)
 *     curated  hand-checked content with a `verifiedAt` date ("verified <date>")
 *     link     a platform MakeItSo only links to (listed under "Links"; HANDSHAKE / DAVIDSON ONE tags appear
 *              only on these curated deep links)
 *     student  entered by the student in MakeItSo
 *     ai       generated by MakeItSo's AI features (always shown with the "AI · verify with your advisor" chip)
 * - `url` is the public home of the source (null for student/AI data).
 *
 * `course-site` (Moodle) is reserved: nothing may use it until T&I approves (PLAN §1).
 */

export const SOURCE_IDS = [
  // api
  "course-schedule",
  "catalog",
  "ratemyprofessors",
  // feed
  "wildcatsync",
  "hurt-hub",
  "library",
  "davidsonian",
  "events-digest",
  "davidson-news",
  // curated
  "registrar",
  "matthews-center",
  "hurt-hub-programs",
  // link
  "handshake",
  "davidson-one",
  "athletics",
  "course-site",
  // student, ai
  "my-plan",
  "ai",
] as const;

export type SourceId = (typeof SOURCE_IDS)[number];

export const SOURCE_KINDS = ["api", "feed", "curated", "link", "student", "ai"] as const;

export type SourceKind = (typeof SOURCE_KINDS)[number];

export interface SourceInfo {
  id: SourceId;
  /** Exact tag text, upper case ("YOUR PLAN"). Always `label.toUpperCase()`. */
  tag: string;
  /** Name in normal case ("Your plan"): what SourceTag and the Sources panel render. */
  label: string;
  kind: SourceKind;
  /** Public home page of the source; null for student-entered and AI data. */
  url: string | null;
  /** Reserved ids are defined but must not be used yet (see `course-site`). */
  reserved?: true;
}

function source(
  id: SourceId,
  label: string,
  kind: SourceKind,
  url: string | null,
  extra: Pick<SourceInfo, "reserved"> = {},
): SourceInfo {
  return { id, tag: label.toUpperCase(), label, kind, url, ...extra };
}

export const SOURCES: Readonly<Record<SourceId, SourceInfo>> = {
  "course-schedule": source(
    "course-schedule",
    "Course schedule",
    "api",
    "https://course-schedule.davidson.edu/",
  ),
  catalog: source("catalog", "Course catalog", "api", "https://catalog.davidson.edu/"),
  ratemyprofessors: source(
    "ratemyprofessors",
    "RateMyProfessors",
    "api",
    "https://www.ratemyprofessors.com/school/3965",
  ),
  wildcatsync: source("wildcatsync", "WildcatSync", "feed", "https://wildcatsync.davidson.edu/"),
  "hurt-hub": source("hurt-hub", "Hurt Hub", "feed", "https://hurthub.davidson.edu/events/"),
  library: source("library", "Library", "feed", "https://www.davidson.edu/library"),
  davidsonian: source("davidsonian", "The Davidsonian", "feed", "https://thedavidsonian.news/"),
  "events-digest": source(
    "events-digest",
    "Events Digest",
    "feed",
    "https://us6.campaign-archive.com/home/?u=a06862fb4e666d96846f036ba&id=2ac4133186",
  ),
  "davidson-news": source(
    "davidson-news",
    "Davidson News",
    "feed",
    "https://www.davidson.edu/news",
  ),
  registrar: source(
    "registrar",
    "Registrar",
    "curated",
    "https://www.davidson.edu/offices-and-services/registrar/academic-calendars/2026-2027",
  ),
  "matthews-center": source(
    "matthews-center",
    "Matthews Center",
    "curated",
    "https://www.davidson.edu/offices-and-services/matthews-center-career-development",
  ),
  "hurt-hub-programs": source(
    "hurt-hub-programs",
    "Hurt Hub programs",
    "curated",
    "https://www.davidson.edu/offices-and-services/jay-hurt-hub-innovation-and-entrepreneurship",
  ),
  handshake: source("handshake", "Handshake", "link", "https://davidson.joinhandshake.com/"),
  "davidson-one": source(
    "davidson-one",
    "Davidson One",
    "link",
    "https://one.davidson.edu/campusm/home#select-profile",
  ),
  athletics: source("athletics", "Athletics", "link", "https://davidsonwildcats.com/calendar"),
  "course-site": source("course-site", "Course site", "link", null, { reserved: true }),
  "my-plan": source("my-plan", "Your plan", "student", null),
  ai: source("ai", "AI", "ai", null),
};

/** Sources MakeItSo syncs itself (kind api or feed): the only ids `fetchExternal` and `recordSync` accept. */
export const SYNCED_SOURCE_IDS = [
  "course-schedule",
  "catalog",
  "ratemyprofessors",
  "wildcatsync",
  "hurt-hub",
  "library",
  "davidsonian",
  "events-digest",
  "davidson-news",
] as const satisfies readonly SourceId[];

export type SyncedSourceId = (typeof SYNCED_SOURCE_IDS)[number];

export function isSourceId(value: unknown): value is SourceId {
  return typeof value === "string" && (SOURCE_IDS as readonly string[]).includes(value);
}

export function isSyncedSourceId(value: unknown): value is SyncedSourceId {
  return typeof value === "string" && (SYNCED_SOURCE_IDS as readonly string[]).includes(value);
}

export function sourceLabel(id: SourceId): string {
  return SOURCES[id].label;
}

/** The exact uppercase tag text for plain-text contexts ("WILDCATSYNC"). */
export function sourceTag(id: SourceId): string {
  return SOURCES[id].tag;
}

/** Every non-reserved source of one kind, in registry order. */
export function sourcesOfKind(kind: SourceKind): SourceInfo[] {
  return SOURCE_IDS.map((id) => SOURCES[id]).filter((s) => s.kind === kind && !s.reserved);
}
